/* ---------------------------------------------------------------------------------------------
 * Copyright (c) Infiniscene, Inc. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 * -------------------------------------------------------------------------------------------- */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apis/layout/v2/api.proto

package stream.api.layout;

/**
 * Protobuf type {@code apis.layout.v2.UpdateLayoutRequest}
 */
public final class UpdateLayoutRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:apis.layout.v2.UpdateLayoutRequest)
    UpdateLayoutRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpdateLayoutRequest.newBuilder() to construct.
  private UpdateLayoutRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateLayoutRequest() {
    layoutId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UpdateLayoutRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UpdateLayoutRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            layoutId_ = s;
            break;
          }
          case 26: {
            stream.api.layout.PartialLayout.Builder subBuilder = null;
            if (layout_ != null) {
              subBuilder = layout_.toBuilder();
            }
            layout_ = input.readMessage(stream.api.layout.PartialLayout.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(layout_);
              layout_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return stream.api.layout.Api.internal_static_apis_layout_v2_UpdateLayoutRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return stream.api.layout.Api.internal_static_apis_layout_v2_UpdateLayoutRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            stream.api.layout.UpdateLayoutRequest.class, stream.api.layout.UpdateLayoutRequest.Builder.class);
  }

  public static final int LAYOUT_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object layoutId_;
  /**
   * <pre>
   * the id of the Layout
   * </pre>
   *
   * <code>string layout_id = 1 [json_name = "layoutId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The layoutId.
   */
  @java.lang.Override
  public java.lang.String getLayoutId() {
    java.lang.Object ref = layoutId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      layoutId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * the id of the Layout
   * </pre>
   *
   * <code>string layout_id = 1 [json_name = "layoutId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for layoutId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLayoutIdBytes() {
    java.lang.Object ref = layoutId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      layoutId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LAYOUT_FIELD_NUMBER = 3;
  private stream.api.layout.PartialLayout layout_;
  /**
   * <pre>
   * layout data to update with.
   * </pre>
   *
   * <code>.apis.layout.v2.PartialLayout layout = 3 [json_name = "layout", (.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the layout field is set.
   */
  @java.lang.Override
  public boolean hasLayout() {
    return layout_ != null;
  }
  /**
   * <pre>
   * layout data to update with.
   * </pre>
   *
   * <code>.apis.layout.v2.PartialLayout layout = 3 [json_name = "layout", (.google.api.field_behavior) = REQUIRED];</code>
   * @return The layout.
   */
  @java.lang.Override
  public stream.api.layout.PartialLayout getLayout() {
    return layout_ == null ? stream.api.layout.PartialLayout.getDefaultInstance() : layout_;
  }
  /**
   * <pre>
   * layout data to update with.
   * </pre>
   *
   * <code>.apis.layout.v2.PartialLayout layout = 3 [json_name = "layout", (.google.api.field_behavior) = REQUIRED];</code>
   */
  @java.lang.Override
  public stream.api.layout.PartialLayoutOrBuilder getLayoutOrBuilder() {
    return getLayout();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(layoutId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, layoutId_);
    }
    if (layout_ != null) {
      output.writeMessage(3, getLayout());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(layoutId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, layoutId_);
    }
    if (layout_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getLayout());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof stream.api.layout.UpdateLayoutRequest)) {
      return super.equals(obj);
    }
    stream.api.layout.UpdateLayoutRequest other = (stream.api.layout.UpdateLayoutRequest) obj;

    if (!getLayoutId()
        .equals(other.getLayoutId())) return false;
    if (hasLayout() != other.hasLayout()) return false;
    if (hasLayout()) {
      if (!getLayout()
          .equals(other.getLayout())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LAYOUT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getLayoutId().hashCode();
    if (hasLayout()) {
      hash = (37 * hash) + LAYOUT_FIELD_NUMBER;
      hash = (53 * hash) + getLayout().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static stream.api.layout.UpdateLayoutRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stream.api.layout.UpdateLayoutRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stream.api.layout.UpdateLayoutRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stream.api.layout.UpdateLayoutRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stream.api.layout.UpdateLayoutRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stream.api.layout.UpdateLayoutRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stream.api.layout.UpdateLayoutRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static stream.api.layout.UpdateLayoutRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static stream.api.layout.UpdateLayoutRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static stream.api.layout.UpdateLayoutRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static stream.api.layout.UpdateLayoutRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static stream.api.layout.UpdateLayoutRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(stream.api.layout.UpdateLayoutRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code apis.layout.v2.UpdateLayoutRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:apis.layout.v2.UpdateLayoutRequest)
      stream.api.layout.UpdateLayoutRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return stream.api.layout.Api.internal_static_apis_layout_v2_UpdateLayoutRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return stream.api.layout.Api.internal_static_apis_layout_v2_UpdateLayoutRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              stream.api.layout.UpdateLayoutRequest.class, stream.api.layout.UpdateLayoutRequest.Builder.class);
    }

    // Construct using stream.api.layout.UpdateLayoutRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      layoutId_ = "";

      if (layoutBuilder_ == null) {
        layout_ = null;
      } else {
        layout_ = null;
        layoutBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return stream.api.layout.Api.internal_static_apis_layout_v2_UpdateLayoutRequest_descriptor;
    }

    @java.lang.Override
    public stream.api.layout.UpdateLayoutRequest getDefaultInstanceForType() {
      return stream.api.layout.UpdateLayoutRequest.getDefaultInstance();
    }

    @java.lang.Override
    public stream.api.layout.UpdateLayoutRequest build() {
      stream.api.layout.UpdateLayoutRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public stream.api.layout.UpdateLayoutRequest buildPartial() {
      stream.api.layout.UpdateLayoutRequest result = new stream.api.layout.UpdateLayoutRequest(this);
      result.layoutId_ = layoutId_;
      if (layoutBuilder_ == null) {
        result.layout_ = layout_;
      } else {
        result.layout_ = layoutBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof stream.api.layout.UpdateLayoutRequest) {
        return mergeFrom((stream.api.layout.UpdateLayoutRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(stream.api.layout.UpdateLayoutRequest other) {
      if (other == stream.api.layout.UpdateLayoutRequest.getDefaultInstance()) return this;
      if (!other.getLayoutId().isEmpty()) {
        layoutId_ = other.layoutId_;
        onChanged();
      }
      if (other.hasLayout()) {
        mergeLayout(other.getLayout());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      stream.api.layout.UpdateLayoutRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (stream.api.layout.UpdateLayoutRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object layoutId_ = "";
    /**
     * <pre>
     * the id of the Layout
     * </pre>
     *
     * <code>string layout_id = 1 [json_name = "layoutId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The layoutId.
     */
    public java.lang.String getLayoutId() {
      java.lang.Object ref = layoutId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        layoutId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * the id of the Layout
     * </pre>
     *
     * <code>string layout_id = 1 [json_name = "layoutId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The bytes for layoutId.
     */
    public com.google.protobuf.ByteString
        getLayoutIdBytes() {
      java.lang.Object ref = layoutId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        layoutId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * the id of the Layout
     * </pre>
     *
     * <code>string layout_id = 1 [json_name = "layoutId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The layoutId to set.
     * @return This builder for chaining.
     */
    public Builder setLayoutId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      layoutId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the id of the Layout
     * </pre>
     *
     * <code>string layout_id = 1 [json_name = "layoutId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearLayoutId() {
      
      layoutId_ = getDefaultInstance().getLayoutId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the id of the Layout
     * </pre>
     *
     * <code>string layout_id = 1 [json_name = "layoutId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The bytes for layoutId to set.
     * @return This builder for chaining.
     */
    public Builder setLayoutIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      layoutId_ = value;
      onChanged();
      return this;
    }

    private stream.api.layout.PartialLayout layout_;
    private com.google.protobuf.SingleFieldBuilderV3<
        stream.api.layout.PartialLayout, stream.api.layout.PartialLayout.Builder, stream.api.layout.PartialLayoutOrBuilder> layoutBuilder_;
    /**
     * <pre>
     * layout data to update with.
     * </pre>
     *
     * <code>.apis.layout.v2.PartialLayout layout = 3 [json_name = "layout", (.google.api.field_behavior) = REQUIRED];</code>
     * @return Whether the layout field is set.
     */
    public boolean hasLayout() {
      return layoutBuilder_ != null || layout_ != null;
    }
    /**
     * <pre>
     * layout data to update with.
     * </pre>
     *
     * <code>.apis.layout.v2.PartialLayout layout = 3 [json_name = "layout", (.google.api.field_behavior) = REQUIRED];</code>
     * @return The layout.
     */
    public stream.api.layout.PartialLayout getLayout() {
      if (layoutBuilder_ == null) {
        return layout_ == null ? stream.api.layout.PartialLayout.getDefaultInstance() : layout_;
      } else {
        return layoutBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * layout data to update with.
     * </pre>
     *
     * <code>.apis.layout.v2.PartialLayout layout = 3 [json_name = "layout", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setLayout(stream.api.layout.PartialLayout value) {
      if (layoutBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        layout_ = value;
        onChanged();
      } else {
        layoutBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * layout data to update with.
     * </pre>
     *
     * <code>.apis.layout.v2.PartialLayout layout = 3 [json_name = "layout", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setLayout(
        stream.api.layout.PartialLayout.Builder builderForValue) {
      if (layoutBuilder_ == null) {
        layout_ = builderForValue.build();
        onChanged();
      } else {
        layoutBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * layout data to update with.
     * </pre>
     *
     * <code>.apis.layout.v2.PartialLayout layout = 3 [json_name = "layout", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder mergeLayout(stream.api.layout.PartialLayout value) {
      if (layoutBuilder_ == null) {
        if (layout_ != null) {
          layout_ =
            stream.api.layout.PartialLayout.newBuilder(layout_).mergeFrom(value).buildPartial();
        } else {
          layout_ = value;
        }
        onChanged();
      } else {
        layoutBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * layout data to update with.
     * </pre>
     *
     * <code>.apis.layout.v2.PartialLayout layout = 3 [json_name = "layout", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder clearLayout() {
      if (layoutBuilder_ == null) {
        layout_ = null;
        onChanged();
      } else {
        layout_ = null;
        layoutBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * layout data to update with.
     * </pre>
     *
     * <code>.apis.layout.v2.PartialLayout layout = 3 [json_name = "layout", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public stream.api.layout.PartialLayout.Builder getLayoutBuilder() {
      
      onChanged();
      return getLayoutFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * layout data to update with.
     * </pre>
     *
     * <code>.apis.layout.v2.PartialLayout layout = 3 [json_name = "layout", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public stream.api.layout.PartialLayoutOrBuilder getLayoutOrBuilder() {
      if (layoutBuilder_ != null) {
        return layoutBuilder_.getMessageOrBuilder();
      } else {
        return layout_ == null ?
            stream.api.layout.PartialLayout.getDefaultInstance() : layout_;
      }
    }
    /**
     * <pre>
     * layout data to update with.
     * </pre>
     *
     * <code>.apis.layout.v2.PartialLayout layout = 3 [json_name = "layout", (.google.api.field_behavior) = REQUIRED];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        stream.api.layout.PartialLayout, stream.api.layout.PartialLayout.Builder, stream.api.layout.PartialLayoutOrBuilder> 
        getLayoutFieldBuilder() {
      if (layoutBuilder_ == null) {
        layoutBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            stream.api.layout.PartialLayout, stream.api.layout.PartialLayout.Builder, stream.api.layout.PartialLayoutOrBuilder>(
                getLayout(),
                getParentForChildren(),
                isClean());
        layout_ = null;
      }
      return layoutBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:apis.layout.v2.UpdateLayoutRequest)
  }

  // @@protoc_insertion_point(class_scope:apis.layout.v2.UpdateLayoutRequest)
  private static final stream.api.layout.UpdateLayoutRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new stream.api.layout.UpdateLayoutRequest();
  }

  public static stream.api.layout.UpdateLayoutRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateLayoutRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdateLayoutRequest>() {
    @java.lang.Override
    public UpdateLayoutRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UpdateLayoutRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UpdateLayoutRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateLayoutRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public stream.api.layout.UpdateLayoutRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

