/* ---------------------------------------------------------------------------------------------
 * Copyright (c) Infiniscene, Inc. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 * -------------------------------------------------------------------------------------------- */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: live/v21/api.proto

package stream.api.live;

public interface CollectionEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:live.v21.CollectionEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.live.v21.CollectionCreateEvent create = 1 [json_name = "create"];</code>
   * @return Whether the create field is set.
   */
  boolean hasCreate();
  /**
   * <code>.live.v21.CollectionCreateEvent create = 1 [json_name = "create"];</code>
   * @return The create.
   */
  stream.api.live.CollectionCreateEvent getCreate();
  /**
   * <code>.live.v21.CollectionCreateEvent create = 1 [json_name = "create"];</code>
   */
  stream.api.live.CollectionCreateEventOrBuilder getCreateOrBuilder();

  /**
   * <code>.live.v21.CollectionUpdateEvent update = 2 [json_name = "update"];</code>
   * @return Whether the update field is set.
   */
  boolean hasUpdate();
  /**
   * <code>.live.v21.CollectionUpdateEvent update = 2 [json_name = "update"];</code>
   * @return The update.
   */
  stream.api.live.CollectionUpdateEvent getUpdate();
  /**
   * <code>.live.v21.CollectionUpdateEvent update = 2 [json_name = "update"];</code>
   */
  stream.api.live.CollectionUpdateEventOrBuilder getUpdateOrBuilder();

  /**
   * <code>.live.v21.CollectionDeleteEvent delete = 3 [json_name = "delete"];</code>
   * @return Whether the delete field is set.
   */
  boolean hasDelete();
  /**
   * <code>.live.v21.CollectionDeleteEvent delete = 3 [json_name = "delete"];</code>
   * @return The delete.
   */
  stream.api.live.CollectionDeleteEvent getDelete();
  /**
   * <code>.live.v21.CollectionDeleteEvent delete = 3 [json_name = "delete"];</code>
   */
  stream.api.live.CollectionDeleteEventOrBuilder getDeleteOrBuilder();

  public stream.api.live.CollectionEvent.TypeCase getTypeCase();
}
