/* ---------------------------------------------------------------------------------------------
 * Copyright (c) Infiniscene, Inc. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 * -------------------------------------------------------------------------------------------- */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: live/v21/api.proto

package stream.api.live;

/**
 * Protobuf type {@code live.v21.CreateProjectRequest}
 */
public final class CreateProjectRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:live.v21.CreateProjectRequest)
    CreateProjectRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateProjectRequest.newBuilder() to construct.
  private CreateProjectRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateProjectRequest() {
    collectionId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateProjectRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateProjectRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            collectionId_ = s;
            break;
          }
          case 18: {
            com.google.protobuf.Value.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) != 0)) {
              subBuilder = metadata_.toBuilder();
            }
            metadata_ = input.readMessage(com.google.protobuf.Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(metadata_);
              metadata_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 26: {
            stream.api.live.Rendering.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) != 0)) {
              subBuilder = rendering_.toBuilder();
            }
            rendering_ = input.readMessage(stream.api.live.Rendering.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(rendering_);
              rendering_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
          case 34: {
            stream.api.live.Encoding.Builder subBuilder = null;
            if (((bitField0_ & 0x00000004) != 0)) {
              subBuilder = encoding_.toBuilder();
            }
            encoding_ = input.readMessage(stream.api.live.Encoding.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(encoding_);
              encoding_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000004;
            break;
          }
          case 42: {
            stream.api.live.Composition.Builder subBuilder = null;
            if (composition_ != null) {
              subBuilder = composition_.toBuilder();
            }
            composition_ = input.readMessage(stream.api.live.Composition.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(composition_);
              composition_ = subBuilder.buildPartial();
            }

            break;
          }
          case 48: {
            bitField0_ |= 0x00000008;
            maxDuration_ = input.readUInt32();
            break;
          }
          case 58: {
            stream.api.live.WebRtc.Builder subBuilder = null;
            if (((bitField0_ & 0x00000010) != 0)) {
              subBuilder = webrtc_.toBuilder();
            }
            webrtc_ = input.readMessage(stream.api.live.WebRtc.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(webrtc_);
              webrtc_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000010;
            break;
          }
          case 74: {
            stream.api.live.LatLong.Builder subBuilder = null;
            if (((bitField0_ & 0x00000020) != 0)) {
              subBuilder = location_.toBuilder();
            }
            location_ = input.readMessage(stream.api.live.LatLong.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(location_);
              location_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000020;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return stream.api.live.Api.internal_static_live_v21_CreateProjectRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return stream.api.live.Api.internal_static_live_v21_CreateProjectRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            stream.api.live.CreateProjectRequest.class, stream.api.live.CreateProjectRequest.Builder.class);
  }

  private int bitField0_;
  public static final int COLLECTION_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object collectionId_;
  /**
   * <pre>
   * collection which will own this project
   * </pre>
   *
   * <code>string collection_id = 1 [json_name = "collectionId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The collectionId.
   */
  @java.lang.Override
  public java.lang.String getCollectionId() {
    java.lang.Object ref = collectionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      collectionId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * collection which will own this project
   * </pre>
   *
   * <code>string collection_id = 1 [json_name = "collectionId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for collectionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCollectionIdBytes() {
    java.lang.Object ref = collectionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      collectionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METADATA_FIELD_NUMBER = 2;
  private com.google.protobuf.Value metadata_;
  /**
   * <pre>
   * arbitrary metadata to associate with this project
   * </pre>
   *
   * <code>optional .google.protobuf.Value metadata = 2 [json_name = "metadata", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the metadata field is set.
   */
  @java.lang.Override
  public boolean hasMetadata() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * arbitrary metadata to associate with this project
   * </pre>
   *
   * <code>optional .google.protobuf.Value metadata = 2 [json_name = "metadata", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The metadata.
   */
  @java.lang.Override
  public com.google.protobuf.Value getMetadata() {
    return metadata_ == null ? com.google.protobuf.Value.getDefaultInstance() : metadata_;
  }
  /**
   * <pre>
   * arbitrary metadata to associate with this project
   * </pre>
   *
   * <code>optional .google.protobuf.Value metadata = 2 [json_name = "metadata", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   */
  @java.lang.Override
  public com.google.protobuf.ValueOrBuilder getMetadataOrBuilder() {
    return metadata_ == null ? com.google.protobuf.Value.getDefaultInstance() : metadata_;
  }

  public static final int RENDERING_FIELD_NUMBER = 3;
  private stream.api.live.Rendering rendering_;
  /**
   * <pre>
   * composition parameters
   * </pre>
   *
   * <code>optional .live.v21.Rendering rendering = 3 [json_name = "rendering", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the rendering field is set.
   */
  @java.lang.Override
  public boolean hasRendering() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * composition parameters
   * </pre>
   *
   * <code>optional .live.v21.Rendering rendering = 3 [json_name = "rendering", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The rendering.
   */
  @java.lang.Override
  public stream.api.live.Rendering getRendering() {
    return rendering_ == null ? stream.api.live.Rendering.getDefaultInstance() : rendering_;
  }
  /**
   * <pre>
   * composition parameters
   * </pre>
   *
   * <code>optional .live.v21.Rendering rendering = 3 [json_name = "rendering", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   */
  @java.lang.Override
  public stream.api.live.RenderingOrBuilder getRenderingOrBuilder() {
    return rendering_ == null ? stream.api.live.Rendering.getDefaultInstance() : rendering_;
  }

  public static final int ENCODING_FIELD_NUMBER = 4;
  private stream.api.live.Encoding encoding_;
  /**
   * <pre>
   * encoding parameters
   * </pre>
   *
   * <code>optional .live.v21.Encoding encoding = 4 [json_name = "encoding", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the encoding field is set.
   */
  @java.lang.Override
  public boolean hasEncoding() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * encoding parameters
   * </pre>
   *
   * <code>optional .live.v21.Encoding encoding = 4 [json_name = "encoding", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The encoding.
   */
  @java.lang.Override
  public stream.api.live.Encoding getEncoding() {
    return encoding_ == null ? stream.api.live.Encoding.getDefaultInstance() : encoding_;
  }
  /**
   * <pre>
   * encoding parameters
   * </pre>
   *
   * <code>optional .live.v21.Encoding encoding = 4 [json_name = "encoding", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   */
  @java.lang.Override
  public stream.api.live.EncodingOrBuilder getEncodingOrBuilder() {
    return encoding_ == null ? stream.api.live.Encoding.getDefaultInstance() : encoding_;
  }

  public static final int COMPOSITION_FIELD_NUMBER = 5;
  private stream.api.live.Composition composition_;
  /**
   * <pre>
   * composition/layout source of the broadcast
   * </pre>
   *
   * <code>.live.v21.Composition composition = 5 [json_name = "composition", (.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the composition field is set.
   */
  @java.lang.Override
  public boolean hasComposition() {
    return composition_ != null;
  }
  /**
   * <pre>
   * composition/layout source of the broadcast
   * </pre>
   *
   * <code>.live.v21.Composition composition = 5 [json_name = "composition", (.google.api.field_behavior) = REQUIRED];</code>
   * @return The composition.
   */
  @java.lang.Override
  public stream.api.live.Composition getComposition() {
    return composition_ == null ? stream.api.live.Composition.getDefaultInstance() : composition_;
  }
  /**
   * <pre>
   * composition/layout source of the broadcast
   * </pre>
   *
   * <code>.live.v21.Composition composition = 5 [json_name = "composition", (.google.api.field_behavior) = REQUIRED];</code>
   */
  @java.lang.Override
  public stream.api.live.CompositionOrBuilder getCompositionOrBuilder() {
    return getComposition();
  }

  public static final int MAX_DURATION_FIELD_NUMBER = 6;
  private int maxDuration_;
  /**
   * <pre>
   * maximum duration of project broadcasts (ms)
   * </pre>
   *
   * <code>optional uint32 max_duration = 6 [json_name = "maxDuration", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the maxDuration field is set.
   */
  @java.lang.Override
  public boolean hasMaxDuration() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * maximum duration of project broadcasts (ms)
   * </pre>
   *
   * <code>optional uint32 max_duration = 6 [json_name = "maxDuration", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The maxDuration.
   */
  @java.lang.Override
  public int getMaxDuration() {
    return maxDuration_;
  }

  public static final int WEBRTC_FIELD_NUMBER = 7;
  private stream.api.live.WebRtc webrtc_;
  /**
   * <pre>
   * request webrtc services
   * </pre>
   *
   * <code>optional .live.v21.WebRtc webrtc = 7 [json_name = "webrtc"];</code>
   * @return Whether the webrtc field is set.
   */
  @java.lang.Override
  public boolean hasWebrtc() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <pre>
   * request webrtc services
   * </pre>
   *
   * <code>optional .live.v21.WebRtc webrtc = 7 [json_name = "webrtc"];</code>
   * @return The webrtc.
   */
  @java.lang.Override
  public stream.api.live.WebRtc getWebrtc() {
    return webrtc_ == null ? stream.api.live.WebRtc.getDefaultInstance() : webrtc_;
  }
  /**
   * <pre>
   * request webrtc services
   * </pre>
   *
   * <code>optional .live.v21.WebRtc webrtc = 7 [json_name = "webrtc"];</code>
   */
  @java.lang.Override
  public stream.api.live.WebRtcOrBuilder getWebrtcOrBuilder() {
    return webrtc_ == null ? stream.api.live.WebRtc.getDefaultInstance() : webrtc_;
  }

  public static final int LOCATION_FIELD_NUMBER = 9;
  private stream.api.live.LatLong location_;
  /**
   * <pre>
   * optimal broadcast location (for routing and delay)
   * </pre>
   *
   * <code>optional .live.v21.LatLong location = 9 [json_name = "location"];</code>
   * @return Whether the location field is set.
   */
  @java.lang.Override
  public boolean hasLocation() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <pre>
   * optimal broadcast location (for routing and delay)
   * </pre>
   *
   * <code>optional .live.v21.LatLong location = 9 [json_name = "location"];</code>
   * @return The location.
   */
  @java.lang.Override
  public stream.api.live.LatLong getLocation() {
    return location_ == null ? stream.api.live.LatLong.getDefaultInstance() : location_;
  }
  /**
   * <pre>
   * optimal broadcast location (for routing and delay)
   * </pre>
   *
   * <code>optional .live.v21.LatLong location = 9 [json_name = "location"];</code>
   */
  @java.lang.Override
  public stream.api.live.LatLongOrBuilder getLocationOrBuilder() {
    return location_ == null ? stream.api.live.LatLong.getDefaultInstance() : location_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(collectionId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, collectionId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getMetadata());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getRendering());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(4, getEncoding());
    }
    if (composition_ != null) {
      output.writeMessage(5, getComposition());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeUInt32(6, maxDuration_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeMessage(7, getWebrtc());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeMessage(9, getLocation());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(collectionId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, collectionId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getMetadata());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getRendering());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getEncoding());
    }
    if (composition_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getComposition());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, maxDuration_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getWebrtc());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getLocation());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof stream.api.live.CreateProjectRequest)) {
      return super.equals(obj);
    }
    stream.api.live.CreateProjectRequest other = (stream.api.live.CreateProjectRequest) obj;

    if (!getCollectionId()
        .equals(other.getCollectionId())) return false;
    if (hasMetadata() != other.hasMetadata()) return false;
    if (hasMetadata()) {
      if (!getMetadata()
          .equals(other.getMetadata())) return false;
    }
    if (hasRendering() != other.hasRendering()) return false;
    if (hasRendering()) {
      if (!getRendering()
          .equals(other.getRendering())) return false;
    }
    if (hasEncoding() != other.hasEncoding()) return false;
    if (hasEncoding()) {
      if (!getEncoding()
          .equals(other.getEncoding())) return false;
    }
    if (hasComposition() != other.hasComposition()) return false;
    if (hasComposition()) {
      if (!getComposition()
          .equals(other.getComposition())) return false;
    }
    if (hasMaxDuration() != other.hasMaxDuration()) return false;
    if (hasMaxDuration()) {
      if (getMaxDuration()
          != other.getMaxDuration()) return false;
    }
    if (hasWebrtc() != other.hasWebrtc()) return false;
    if (hasWebrtc()) {
      if (!getWebrtc()
          .equals(other.getWebrtc())) return false;
    }
    if (hasLocation() != other.hasLocation()) return false;
    if (hasLocation()) {
      if (!getLocation()
          .equals(other.getLocation())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COLLECTION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCollectionId().hashCode();
    if (hasMetadata()) {
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetadata().hashCode();
    }
    if (hasRendering()) {
      hash = (37 * hash) + RENDERING_FIELD_NUMBER;
      hash = (53 * hash) + getRendering().hashCode();
    }
    if (hasEncoding()) {
      hash = (37 * hash) + ENCODING_FIELD_NUMBER;
      hash = (53 * hash) + getEncoding().hashCode();
    }
    if (hasComposition()) {
      hash = (37 * hash) + COMPOSITION_FIELD_NUMBER;
      hash = (53 * hash) + getComposition().hashCode();
    }
    if (hasMaxDuration()) {
      hash = (37 * hash) + MAX_DURATION_FIELD_NUMBER;
      hash = (53 * hash) + getMaxDuration();
    }
    if (hasWebrtc()) {
      hash = (37 * hash) + WEBRTC_FIELD_NUMBER;
      hash = (53 * hash) + getWebrtc().hashCode();
    }
    if (hasLocation()) {
      hash = (37 * hash) + LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getLocation().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static stream.api.live.CreateProjectRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stream.api.live.CreateProjectRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stream.api.live.CreateProjectRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stream.api.live.CreateProjectRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stream.api.live.CreateProjectRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stream.api.live.CreateProjectRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stream.api.live.CreateProjectRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static stream.api.live.CreateProjectRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static stream.api.live.CreateProjectRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static stream.api.live.CreateProjectRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static stream.api.live.CreateProjectRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static stream.api.live.CreateProjectRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(stream.api.live.CreateProjectRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code live.v21.CreateProjectRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:live.v21.CreateProjectRequest)
      stream.api.live.CreateProjectRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return stream.api.live.Api.internal_static_live_v21_CreateProjectRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return stream.api.live.Api.internal_static_live_v21_CreateProjectRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              stream.api.live.CreateProjectRequest.class, stream.api.live.CreateProjectRequest.Builder.class);
    }

    // Construct using stream.api.live.CreateProjectRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMetadataFieldBuilder();
        getRenderingFieldBuilder();
        getEncodingFieldBuilder();
        getWebrtcFieldBuilder();
        getLocationFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      collectionId_ = "";

      if (metadataBuilder_ == null) {
        metadata_ = null;
      } else {
        metadataBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (renderingBuilder_ == null) {
        rendering_ = null;
      } else {
        renderingBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (encodingBuilder_ == null) {
        encoding_ = null;
      } else {
        encodingBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      if (compositionBuilder_ == null) {
        composition_ = null;
      } else {
        composition_ = null;
        compositionBuilder_ = null;
      }
      maxDuration_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      if (webrtcBuilder_ == null) {
        webrtc_ = null;
      } else {
        webrtcBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      if (locationBuilder_ == null) {
        location_ = null;
      } else {
        locationBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return stream.api.live.Api.internal_static_live_v21_CreateProjectRequest_descriptor;
    }

    @java.lang.Override
    public stream.api.live.CreateProjectRequest getDefaultInstanceForType() {
      return stream.api.live.CreateProjectRequest.getDefaultInstance();
    }

    @java.lang.Override
    public stream.api.live.CreateProjectRequest build() {
      stream.api.live.CreateProjectRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public stream.api.live.CreateProjectRequest buildPartial() {
      stream.api.live.CreateProjectRequest result = new stream.api.live.CreateProjectRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.collectionId_ = collectionId_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        if (metadataBuilder_ == null) {
          result.metadata_ = metadata_;
        } else {
          result.metadata_ = metadataBuilder_.build();
        }
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        if (renderingBuilder_ == null) {
          result.rendering_ = rendering_;
        } else {
          result.rendering_ = renderingBuilder_.build();
        }
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        if (encodingBuilder_ == null) {
          result.encoding_ = encoding_;
        } else {
          result.encoding_ = encodingBuilder_.build();
        }
        to_bitField0_ |= 0x00000004;
      }
      if (compositionBuilder_ == null) {
        result.composition_ = composition_;
      } else {
        result.composition_ = compositionBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.maxDuration_ = maxDuration_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        if (webrtcBuilder_ == null) {
          result.webrtc_ = webrtc_;
        } else {
          result.webrtc_ = webrtcBuilder_.build();
        }
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        if (locationBuilder_ == null) {
          result.location_ = location_;
        } else {
          result.location_ = locationBuilder_.build();
        }
        to_bitField0_ |= 0x00000020;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof stream.api.live.CreateProjectRequest) {
        return mergeFrom((stream.api.live.CreateProjectRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(stream.api.live.CreateProjectRequest other) {
      if (other == stream.api.live.CreateProjectRequest.getDefaultInstance()) return this;
      if (!other.getCollectionId().isEmpty()) {
        collectionId_ = other.collectionId_;
        onChanged();
      }
      if (other.hasMetadata()) {
        mergeMetadata(other.getMetadata());
      }
      if (other.hasRendering()) {
        mergeRendering(other.getRendering());
      }
      if (other.hasEncoding()) {
        mergeEncoding(other.getEncoding());
      }
      if (other.hasComposition()) {
        mergeComposition(other.getComposition());
      }
      if (other.hasMaxDuration()) {
        setMaxDuration(other.getMaxDuration());
      }
      if (other.hasWebrtc()) {
        mergeWebrtc(other.getWebrtc());
      }
      if (other.hasLocation()) {
        mergeLocation(other.getLocation());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      stream.api.live.CreateProjectRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (stream.api.live.CreateProjectRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object collectionId_ = "";
    /**
     * <pre>
     * collection which will own this project
     * </pre>
     *
     * <code>string collection_id = 1 [json_name = "collectionId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The collectionId.
     */
    public java.lang.String getCollectionId() {
      java.lang.Object ref = collectionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        collectionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * collection which will own this project
     * </pre>
     *
     * <code>string collection_id = 1 [json_name = "collectionId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The bytes for collectionId.
     */
    public com.google.protobuf.ByteString
        getCollectionIdBytes() {
      java.lang.Object ref = collectionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        collectionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * collection which will own this project
     * </pre>
     *
     * <code>string collection_id = 1 [json_name = "collectionId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The collectionId to set.
     * @return This builder for chaining.
     */
    public Builder setCollectionId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      collectionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * collection which will own this project
     * </pre>
     *
     * <code>string collection_id = 1 [json_name = "collectionId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearCollectionId() {
      
      collectionId_ = getDefaultInstance().getCollectionId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * collection which will own this project
     * </pre>
     *
     * <code>string collection_id = 1 [json_name = "collectionId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The bytes for collectionId to set.
     * @return This builder for chaining.
     */
    public Builder setCollectionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      collectionId_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Value metadata_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Value, com.google.protobuf.Value.Builder, com.google.protobuf.ValueOrBuilder> metadataBuilder_;
    /**
     * <pre>
     * arbitrary metadata to associate with this project
     * </pre>
     *
     * <code>optional .google.protobuf.Value metadata = 2 [json_name = "metadata", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return Whether the metadata field is set.
     */
    public boolean hasMetadata() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * arbitrary metadata to associate with this project
     * </pre>
     *
     * <code>optional .google.protobuf.Value metadata = 2 [json_name = "metadata", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The metadata.
     */
    public com.google.protobuf.Value getMetadata() {
      if (metadataBuilder_ == null) {
        return metadata_ == null ? com.google.protobuf.Value.getDefaultInstance() : metadata_;
      } else {
        return metadataBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * arbitrary metadata to associate with this project
     * </pre>
     *
     * <code>optional .google.protobuf.Value metadata = 2 [json_name = "metadata", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder setMetadata(com.google.protobuf.Value value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metadata_ = value;
        onChanged();
      } else {
        metadataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * arbitrary metadata to associate with this project
     * </pre>
     *
     * <code>optional .google.protobuf.Value metadata = 2 [json_name = "metadata", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder setMetadata(
        com.google.protobuf.Value.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        metadata_ = builderForValue.build();
        onChanged();
      } else {
        metadataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * arbitrary metadata to associate with this project
     * </pre>
     *
     * <code>optional .google.protobuf.Value metadata = 2 [json_name = "metadata", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder mergeMetadata(com.google.protobuf.Value value) {
      if (metadataBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
            metadata_ != null &&
            metadata_ != com.google.protobuf.Value.getDefaultInstance()) {
          metadata_ =
            com.google.protobuf.Value.newBuilder(metadata_).mergeFrom(value).buildPartial();
        } else {
          metadata_ = value;
        }
        onChanged();
      } else {
        metadataBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * arbitrary metadata to associate with this project
     * </pre>
     *
     * <code>optional .google.protobuf.Value metadata = 2 [json_name = "metadata", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder clearMetadata() {
      if (metadataBuilder_ == null) {
        metadata_ = null;
        onChanged();
      } else {
        metadataBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <pre>
     * arbitrary metadata to associate with this project
     * </pre>
     *
     * <code>optional .google.protobuf.Value metadata = 2 [json_name = "metadata", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public com.google.protobuf.Value.Builder getMetadataBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getMetadataFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * arbitrary metadata to associate with this project
     * </pre>
     *
     * <code>optional .google.protobuf.Value metadata = 2 [json_name = "metadata", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public com.google.protobuf.ValueOrBuilder getMetadataOrBuilder() {
      if (metadataBuilder_ != null) {
        return metadataBuilder_.getMessageOrBuilder();
      } else {
        return metadata_ == null ?
            com.google.protobuf.Value.getDefaultInstance() : metadata_;
      }
    }
    /**
     * <pre>
     * arbitrary metadata to associate with this project
     * </pre>
     *
     * <code>optional .google.protobuf.Value metadata = 2 [json_name = "metadata", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Value, com.google.protobuf.Value.Builder, com.google.protobuf.ValueOrBuilder> 
        getMetadataFieldBuilder() {
      if (metadataBuilder_ == null) {
        metadataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Value, com.google.protobuf.Value.Builder, com.google.protobuf.ValueOrBuilder>(
                getMetadata(),
                getParentForChildren(),
                isClean());
        metadata_ = null;
      }
      return metadataBuilder_;
    }

    private stream.api.live.Rendering rendering_;
    private com.google.protobuf.SingleFieldBuilderV3<
        stream.api.live.Rendering, stream.api.live.Rendering.Builder, stream.api.live.RenderingOrBuilder> renderingBuilder_;
    /**
     * <pre>
     * composition parameters
     * </pre>
     *
     * <code>optional .live.v21.Rendering rendering = 3 [json_name = "rendering", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return Whether the rendering field is set.
     */
    public boolean hasRendering() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * composition parameters
     * </pre>
     *
     * <code>optional .live.v21.Rendering rendering = 3 [json_name = "rendering", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The rendering.
     */
    public stream.api.live.Rendering getRendering() {
      if (renderingBuilder_ == null) {
        return rendering_ == null ? stream.api.live.Rendering.getDefaultInstance() : rendering_;
      } else {
        return renderingBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * composition parameters
     * </pre>
     *
     * <code>optional .live.v21.Rendering rendering = 3 [json_name = "rendering", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder setRendering(stream.api.live.Rendering value) {
      if (renderingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        rendering_ = value;
        onChanged();
      } else {
        renderingBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <pre>
     * composition parameters
     * </pre>
     *
     * <code>optional .live.v21.Rendering rendering = 3 [json_name = "rendering", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder setRendering(
        stream.api.live.Rendering.Builder builderForValue) {
      if (renderingBuilder_ == null) {
        rendering_ = builderForValue.build();
        onChanged();
      } else {
        renderingBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <pre>
     * composition parameters
     * </pre>
     *
     * <code>optional .live.v21.Rendering rendering = 3 [json_name = "rendering", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder mergeRendering(stream.api.live.Rendering value) {
      if (renderingBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
            rendering_ != null &&
            rendering_ != stream.api.live.Rendering.getDefaultInstance()) {
          rendering_ =
            stream.api.live.Rendering.newBuilder(rendering_).mergeFrom(value).buildPartial();
        } else {
          rendering_ = value;
        }
        onChanged();
      } else {
        renderingBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <pre>
     * composition parameters
     * </pre>
     *
     * <code>optional .live.v21.Rendering rendering = 3 [json_name = "rendering", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder clearRendering() {
      if (renderingBuilder_ == null) {
        rendering_ = null;
        onChanged();
      } else {
        renderingBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <pre>
     * composition parameters
     * </pre>
     *
     * <code>optional .live.v21.Rendering rendering = 3 [json_name = "rendering", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public stream.api.live.Rendering.Builder getRenderingBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getRenderingFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * composition parameters
     * </pre>
     *
     * <code>optional .live.v21.Rendering rendering = 3 [json_name = "rendering", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public stream.api.live.RenderingOrBuilder getRenderingOrBuilder() {
      if (renderingBuilder_ != null) {
        return renderingBuilder_.getMessageOrBuilder();
      } else {
        return rendering_ == null ?
            stream.api.live.Rendering.getDefaultInstance() : rendering_;
      }
    }
    /**
     * <pre>
     * composition parameters
     * </pre>
     *
     * <code>optional .live.v21.Rendering rendering = 3 [json_name = "rendering", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        stream.api.live.Rendering, stream.api.live.Rendering.Builder, stream.api.live.RenderingOrBuilder> 
        getRenderingFieldBuilder() {
      if (renderingBuilder_ == null) {
        renderingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            stream.api.live.Rendering, stream.api.live.Rendering.Builder, stream.api.live.RenderingOrBuilder>(
                getRendering(),
                getParentForChildren(),
                isClean());
        rendering_ = null;
      }
      return renderingBuilder_;
    }

    private stream.api.live.Encoding encoding_;
    private com.google.protobuf.SingleFieldBuilderV3<
        stream.api.live.Encoding, stream.api.live.Encoding.Builder, stream.api.live.EncodingOrBuilder> encodingBuilder_;
    /**
     * <pre>
     * encoding parameters
     * </pre>
     *
     * <code>optional .live.v21.Encoding encoding = 4 [json_name = "encoding", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return Whether the encoding field is set.
     */
    public boolean hasEncoding() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * encoding parameters
     * </pre>
     *
     * <code>optional .live.v21.Encoding encoding = 4 [json_name = "encoding", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The encoding.
     */
    public stream.api.live.Encoding getEncoding() {
      if (encodingBuilder_ == null) {
        return encoding_ == null ? stream.api.live.Encoding.getDefaultInstance() : encoding_;
      } else {
        return encodingBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * encoding parameters
     * </pre>
     *
     * <code>optional .live.v21.Encoding encoding = 4 [json_name = "encoding", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder setEncoding(stream.api.live.Encoding value) {
      if (encodingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        encoding_ = value;
        onChanged();
      } else {
        encodingBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <pre>
     * encoding parameters
     * </pre>
     *
     * <code>optional .live.v21.Encoding encoding = 4 [json_name = "encoding", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder setEncoding(
        stream.api.live.Encoding.Builder builderForValue) {
      if (encodingBuilder_ == null) {
        encoding_ = builderForValue.build();
        onChanged();
      } else {
        encodingBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <pre>
     * encoding parameters
     * </pre>
     *
     * <code>optional .live.v21.Encoding encoding = 4 [json_name = "encoding", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder mergeEncoding(stream.api.live.Encoding value) {
      if (encodingBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
            encoding_ != null &&
            encoding_ != stream.api.live.Encoding.getDefaultInstance()) {
          encoding_ =
            stream.api.live.Encoding.newBuilder(encoding_).mergeFrom(value).buildPartial();
        } else {
          encoding_ = value;
        }
        onChanged();
      } else {
        encodingBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <pre>
     * encoding parameters
     * </pre>
     *
     * <code>optional .live.v21.Encoding encoding = 4 [json_name = "encoding", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder clearEncoding() {
      if (encodingBuilder_ == null) {
        encoding_ = null;
        onChanged();
      } else {
        encodingBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }
    /**
     * <pre>
     * encoding parameters
     * </pre>
     *
     * <code>optional .live.v21.Encoding encoding = 4 [json_name = "encoding", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public stream.api.live.Encoding.Builder getEncodingBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getEncodingFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * encoding parameters
     * </pre>
     *
     * <code>optional .live.v21.Encoding encoding = 4 [json_name = "encoding", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public stream.api.live.EncodingOrBuilder getEncodingOrBuilder() {
      if (encodingBuilder_ != null) {
        return encodingBuilder_.getMessageOrBuilder();
      } else {
        return encoding_ == null ?
            stream.api.live.Encoding.getDefaultInstance() : encoding_;
      }
    }
    /**
     * <pre>
     * encoding parameters
     * </pre>
     *
     * <code>optional .live.v21.Encoding encoding = 4 [json_name = "encoding", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        stream.api.live.Encoding, stream.api.live.Encoding.Builder, stream.api.live.EncodingOrBuilder> 
        getEncodingFieldBuilder() {
      if (encodingBuilder_ == null) {
        encodingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            stream.api.live.Encoding, stream.api.live.Encoding.Builder, stream.api.live.EncodingOrBuilder>(
                getEncoding(),
                getParentForChildren(),
                isClean());
        encoding_ = null;
      }
      return encodingBuilder_;
    }

    private stream.api.live.Composition composition_;
    private com.google.protobuf.SingleFieldBuilderV3<
        stream.api.live.Composition, stream.api.live.Composition.Builder, stream.api.live.CompositionOrBuilder> compositionBuilder_;
    /**
     * <pre>
     * composition/layout source of the broadcast
     * </pre>
     *
     * <code>.live.v21.Composition composition = 5 [json_name = "composition", (.google.api.field_behavior) = REQUIRED];</code>
     * @return Whether the composition field is set.
     */
    public boolean hasComposition() {
      return compositionBuilder_ != null || composition_ != null;
    }
    /**
     * <pre>
     * composition/layout source of the broadcast
     * </pre>
     *
     * <code>.live.v21.Composition composition = 5 [json_name = "composition", (.google.api.field_behavior) = REQUIRED];</code>
     * @return The composition.
     */
    public stream.api.live.Composition getComposition() {
      if (compositionBuilder_ == null) {
        return composition_ == null ? stream.api.live.Composition.getDefaultInstance() : composition_;
      } else {
        return compositionBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * composition/layout source of the broadcast
     * </pre>
     *
     * <code>.live.v21.Composition composition = 5 [json_name = "composition", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setComposition(stream.api.live.Composition value) {
      if (compositionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        composition_ = value;
        onChanged();
      } else {
        compositionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * composition/layout source of the broadcast
     * </pre>
     *
     * <code>.live.v21.Composition composition = 5 [json_name = "composition", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setComposition(
        stream.api.live.Composition.Builder builderForValue) {
      if (compositionBuilder_ == null) {
        composition_ = builderForValue.build();
        onChanged();
      } else {
        compositionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * composition/layout source of the broadcast
     * </pre>
     *
     * <code>.live.v21.Composition composition = 5 [json_name = "composition", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder mergeComposition(stream.api.live.Composition value) {
      if (compositionBuilder_ == null) {
        if (composition_ != null) {
          composition_ =
            stream.api.live.Composition.newBuilder(composition_).mergeFrom(value).buildPartial();
        } else {
          composition_ = value;
        }
        onChanged();
      } else {
        compositionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * composition/layout source of the broadcast
     * </pre>
     *
     * <code>.live.v21.Composition composition = 5 [json_name = "composition", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder clearComposition() {
      if (compositionBuilder_ == null) {
        composition_ = null;
        onChanged();
      } else {
        composition_ = null;
        compositionBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * composition/layout source of the broadcast
     * </pre>
     *
     * <code>.live.v21.Composition composition = 5 [json_name = "composition", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public stream.api.live.Composition.Builder getCompositionBuilder() {
      
      onChanged();
      return getCompositionFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * composition/layout source of the broadcast
     * </pre>
     *
     * <code>.live.v21.Composition composition = 5 [json_name = "composition", (.google.api.field_behavior) = REQUIRED];</code>
     */
    public stream.api.live.CompositionOrBuilder getCompositionOrBuilder() {
      if (compositionBuilder_ != null) {
        return compositionBuilder_.getMessageOrBuilder();
      } else {
        return composition_ == null ?
            stream.api.live.Composition.getDefaultInstance() : composition_;
      }
    }
    /**
     * <pre>
     * composition/layout source of the broadcast
     * </pre>
     *
     * <code>.live.v21.Composition composition = 5 [json_name = "composition", (.google.api.field_behavior) = REQUIRED];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        stream.api.live.Composition, stream.api.live.Composition.Builder, stream.api.live.CompositionOrBuilder> 
        getCompositionFieldBuilder() {
      if (compositionBuilder_ == null) {
        compositionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            stream.api.live.Composition, stream.api.live.Composition.Builder, stream.api.live.CompositionOrBuilder>(
                getComposition(),
                getParentForChildren(),
                isClean());
        composition_ = null;
      }
      return compositionBuilder_;
    }

    private int maxDuration_ ;
    /**
     * <pre>
     * maximum duration of project broadcasts (ms)
     * </pre>
     *
     * <code>optional uint32 max_duration = 6 [json_name = "maxDuration", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return Whether the maxDuration field is set.
     */
    @java.lang.Override
    public boolean hasMaxDuration() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * maximum duration of project broadcasts (ms)
     * </pre>
     *
     * <code>optional uint32 max_duration = 6 [json_name = "maxDuration", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The maxDuration.
     */
    @java.lang.Override
    public int getMaxDuration() {
      return maxDuration_;
    }
    /**
     * <pre>
     * maximum duration of project broadcasts (ms)
     * </pre>
     *
     * <code>optional uint32 max_duration = 6 [json_name = "maxDuration", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The maxDuration to set.
     * @return This builder for chaining.
     */
    public Builder setMaxDuration(int value) {
      bitField0_ |= 0x00000008;
      maxDuration_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * maximum duration of project broadcasts (ms)
     * </pre>
     *
     * <code>optional uint32 max_duration = 6 [json_name = "maxDuration", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxDuration() {
      bitField0_ = (bitField0_ & ~0x00000008);
      maxDuration_ = 0;
      onChanged();
      return this;
    }

    private stream.api.live.WebRtc webrtc_;
    private com.google.protobuf.SingleFieldBuilderV3<
        stream.api.live.WebRtc, stream.api.live.WebRtc.Builder, stream.api.live.WebRtcOrBuilder> webrtcBuilder_;
    /**
     * <pre>
     * request webrtc services
     * </pre>
     *
     * <code>optional .live.v21.WebRtc webrtc = 7 [json_name = "webrtc"];</code>
     * @return Whether the webrtc field is set.
     */
    public boolean hasWebrtc() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * request webrtc services
     * </pre>
     *
     * <code>optional .live.v21.WebRtc webrtc = 7 [json_name = "webrtc"];</code>
     * @return The webrtc.
     */
    public stream.api.live.WebRtc getWebrtc() {
      if (webrtcBuilder_ == null) {
        return webrtc_ == null ? stream.api.live.WebRtc.getDefaultInstance() : webrtc_;
      } else {
        return webrtcBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * request webrtc services
     * </pre>
     *
     * <code>optional .live.v21.WebRtc webrtc = 7 [json_name = "webrtc"];</code>
     */
    public Builder setWebrtc(stream.api.live.WebRtc value) {
      if (webrtcBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        webrtc_ = value;
        onChanged();
      } else {
        webrtcBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <pre>
     * request webrtc services
     * </pre>
     *
     * <code>optional .live.v21.WebRtc webrtc = 7 [json_name = "webrtc"];</code>
     */
    public Builder setWebrtc(
        stream.api.live.WebRtc.Builder builderForValue) {
      if (webrtcBuilder_ == null) {
        webrtc_ = builderForValue.build();
        onChanged();
      } else {
        webrtcBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <pre>
     * request webrtc services
     * </pre>
     *
     * <code>optional .live.v21.WebRtc webrtc = 7 [json_name = "webrtc"];</code>
     */
    public Builder mergeWebrtc(stream.api.live.WebRtc value) {
      if (webrtcBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
            webrtc_ != null &&
            webrtc_ != stream.api.live.WebRtc.getDefaultInstance()) {
          webrtc_ =
            stream.api.live.WebRtc.newBuilder(webrtc_).mergeFrom(value).buildPartial();
        } else {
          webrtc_ = value;
        }
        onChanged();
      } else {
        webrtcBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <pre>
     * request webrtc services
     * </pre>
     *
     * <code>optional .live.v21.WebRtc webrtc = 7 [json_name = "webrtc"];</code>
     */
    public Builder clearWebrtc() {
      if (webrtcBuilder_ == null) {
        webrtc_ = null;
        onChanged();
      } else {
        webrtcBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }
    /**
     * <pre>
     * request webrtc services
     * </pre>
     *
     * <code>optional .live.v21.WebRtc webrtc = 7 [json_name = "webrtc"];</code>
     */
    public stream.api.live.WebRtc.Builder getWebrtcBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getWebrtcFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * request webrtc services
     * </pre>
     *
     * <code>optional .live.v21.WebRtc webrtc = 7 [json_name = "webrtc"];</code>
     */
    public stream.api.live.WebRtcOrBuilder getWebrtcOrBuilder() {
      if (webrtcBuilder_ != null) {
        return webrtcBuilder_.getMessageOrBuilder();
      } else {
        return webrtc_ == null ?
            stream.api.live.WebRtc.getDefaultInstance() : webrtc_;
      }
    }
    /**
     * <pre>
     * request webrtc services
     * </pre>
     *
     * <code>optional .live.v21.WebRtc webrtc = 7 [json_name = "webrtc"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        stream.api.live.WebRtc, stream.api.live.WebRtc.Builder, stream.api.live.WebRtcOrBuilder> 
        getWebrtcFieldBuilder() {
      if (webrtcBuilder_ == null) {
        webrtcBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            stream.api.live.WebRtc, stream.api.live.WebRtc.Builder, stream.api.live.WebRtcOrBuilder>(
                getWebrtc(),
                getParentForChildren(),
                isClean());
        webrtc_ = null;
      }
      return webrtcBuilder_;
    }

    private stream.api.live.LatLong location_;
    private com.google.protobuf.SingleFieldBuilderV3<
        stream.api.live.LatLong, stream.api.live.LatLong.Builder, stream.api.live.LatLongOrBuilder> locationBuilder_;
    /**
     * <pre>
     * optimal broadcast location (for routing and delay)
     * </pre>
     *
     * <code>optional .live.v21.LatLong location = 9 [json_name = "location"];</code>
     * @return Whether the location field is set.
     */
    public boolean hasLocation() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * optimal broadcast location (for routing and delay)
     * </pre>
     *
     * <code>optional .live.v21.LatLong location = 9 [json_name = "location"];</code>
     * @return The location.
     */
    public stream.api.live.LatLong getLocation() {
      if (locationBuilder_ == null) {
        return location_ == null ? stream.api.live.LatLong.getDefaultInstance() : location_;
      } else {
        return locationBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * optimal broadcast location (for routing and delay)
     * </pre>
     *
     * <code>optional .live.v21.LatLong location = 9 [json_name = "location"];</code>
     */
    public Builder setLocation(stream.api.live.LatLong value) {
      if (locationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        location_ = value;
        onChanged();
      } else {
        locationBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <pre>
     * optimal broadcast location (for routing and delay)
     * </pre>
     *
     * <code>optional .live.v21.LatLong location = 9 [json_name = "location"];</code>
     */
    public Builder setLocation(
        stream.api.live.LatLong.Builder builderForValue) {
      if (locationBuilder_ == null) {
        location_ = builderForValue.build();
        onChanged();
      } else {
        locationBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <pre>
     * optimal broadcast location (for routing and delay)
     * </pre>
     *
     * <code>optional .live.v21.LatLong location = 9 [json_name = "location"];</code>
     */
    public Builder mergeLocation(stream.api.live.LatLong value) {
      if (locationBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
            location_ != null &&
            location_ != stream.api.live.LatLong.getDefaultInstance()) {
          location_ =
            stream.api.live.LatLong.newBuilder(location_).mergeFrom(value).buildPartial();
        } else {
          location_ = value;
        }
        onChanged();
      } else {
        locationBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <pre>
     * optimal broadcast location (for routing and delay)
     * </pre>
     *
     * <code>optional .live.v21.LatLong location = 9 [json_name = "location"];</code>
     */
    public Builder clearLocation() {
      if (locationBuilder_ == null) {
        location_ = null;
        onChanged();
      } else {
        locationBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }
    /**
     * <pre>
     * optimal broadcast location (for routing and delay)
     * </pre>
     *
     * <code>optional .live.v21.LatLong location = 9 [json_name = "location"];</code>
     */
    public stream.api.live.LatLong.Builder getLocationBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getLocationFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * optimal broadcast location (for routing and delay)
     * </pre>
     *
     * <code>optional .live.v21.LatLong location = 9 [json_name = "location"];</code>
     */
    public stream.api.live.LatLongOrBuilder getLocationOrBuilder() {
      if (locationBuilder_ != null) {
        return locationBuilder_.getMessageOrBuilder();
      } else {
        return location_ == null ?
            stream.api.live.LatLong.getDefaultInstance() : location_;
      }
    }
    /**
     * <pre>
     * optimal broadcast location (for routing and delay)
     * </pre>
     *
     * <code>optional .live.v21.LatLong location = 9 [json_name = "location"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        stream.api.live.LatLong, stream.api.live.LatLong.Builder, stream.api.live.LatLongOrBuilder> 
        getLocationFieldBuilder() {
      if (locationBuilder_ == null) {
        locationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            stream.api.live.LatLong, stream.api.live.LatLong.Builder, stream.api.live.LatLongOrBuilder>(
                getLocation(),
                getParentForChildren(),
                isClean());
        location_ = null;
      }
      return locationBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:live.v21.CreateProjectRequest)
  }

  // @@protoc_insertion_point(class_scope:live.v21.CreateProjectRequest)
  private static final stream.api.live.CreateProjectRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new stream.api.live.CreateProjectRequest();
  }

  public static stream.api.live.CreateProjectRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateProjectRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateProjectRequest>() {
    @java.lang.Override
    public CreateProjectRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateProjectRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateProjectRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateProjectRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public stream.api.live.CreateProjectRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

