/* ---------------------------------------------------------------------------------------------
 * Copyright (c) Infiniscene, Inc. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 * -------------------------------------------------------------------------------------------- */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: live/v21/api.proto

package stream.api.live;

public interface DeleteCollectionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:live.v21.DeleteCollectionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * collection id
   * </pre>
   *
   * <code>string collection_id = 1 [json_name = "collectionId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The collectionId.
   */
  java.lang.String getCollectionId();
  /**
   * <pre>
   * collection id
   * </pre>
   *
   * <code>string collection_id = 1 [json_name = "collectionId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for collectionId.
   */
  com.google.protobuf.ByteString
      getCollectionIdBytes();

  /**
   * <pre>
   * forcibly end all child project broadcasts in progress
   * </pre>
   *
   * <code>optional bool force = 2 [json_name = "force", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the force field is set.
   */
  boolean hasForce();
  /**
   * <pre>
   * forcibly end all child project broadcasts in progress
   * </pre>
   *
   * <code>optional bool force = 2 [json_name = "force", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The force.
   */
  boolean getForce();
}
