/* ---------------------------------------------------------------------------------------------
 * Copyright (c) Infiniscene, Inc. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 * -------------------------------------------------------------------------------------------- */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: live/v21/api.proto

package stream.api.live;

/**
 * <pre>
 * a destination was updated
 * </pre>
 *
 * Protobuf type {@code live.v21.DestinationUpdateEvent}
 */
public final class DestinationUpdateEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:live.v21.DestinationUpdateEvent)
    DestinationUpdateEventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DestinationUpdateEvent.newBuilder() to construct.
  private DestinationUpdateEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DestinationUpdateEvent() {
    collectionId_ = "";
    projectId_ = "";
    destinationId_ = "";
    updateMask_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DestinationUpdateEvent();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DestinationUpdateEvent(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            collectionId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            projectId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            destinationId_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              updateMask_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            updateMask_.add(s);
            break;
          }
          case 42: {
            stream.api.live.Destination.Builder subBuilder = null;
            if (destination_ != null) {
              subBuilder = destination_.toBuilder();
            }
            destination_ = input.readMessage(stream.api.live.Destination.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(destination_);
              destination_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        updateMask_ = updateMask_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return stream.api.live.Api.internal_static_live_v21_DestinationUpdateEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return stream.api.live.Api.internal_static_live_v21_DestinationUpdateEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            stream.api.live.DestinationUpdateEvent.class, stream.api.live.DestinationUpdateEvent.Builder.class);
  }

  public static final int COLLECTION_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object collectionId_;
  /**
   * <pre>
   * collection which owns the project which owns the destination
   * </pre>
   *
   * <code>string collection_id = 1 [json_name = "collectionId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The collectionId.
   */
  @java.lang.Override
  public java.lang.String getCollectionId() {
    java.lang.Object ref = collectionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      collectionId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * collection which owns the project which owns the destination
   * </pre>
   *
   * <code>string collection_id = 1 [json_name = "collectionId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for collectionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCollectionIdBytes() {
    java.lang.Object ref = collectionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      collectionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROJECT_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object projectId_;
  /**
   * <pre>
   * project which owns the destination
   * </pre>
   *
   * <code>string project_id = 2 [json_name = "projectId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The projectId.
   */
  @java.lang.Override
  public java.lang.String getProjectId() {
    java.lang.Object ref = projectId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      projectId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * project which owns the destination
   * </pre>
   *
   * <code>string project_id = 2 [json_name = "projectId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for projectId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProjectIdBytes() {
    java.lang.Object ref = projectId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      projectId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESTINATION_ID_FIELD_NUMBER = 3;
  private volatile java.lang.Object destinationId_;
  /**
   * <pre>
   * destination id
   * </pre>
   *
   * <code>string destination_id = 3 [json_name = "destinationId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The destinationId.
   */
  @java.lang.Override
  public java.lang.String getDestinationId() {
    java.lang.Object ref = destinationId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      destinationId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * destination id
   * </pre>
   *
   * <code>string destination_id = 3 [json_name = "destinationId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for destinationId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDestinationIdBytes() {
    java.lang.Object ref = destinationId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      destinationId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UPDATE_MASK_FIELD_NUMBER = 4;
  private com.google.protobuf.LazyStringList updateMask_;
  /**
   * <pre>
   * changed fields
   * </pre>
   *
   * <code>repeated string update_mask = 4 [json_name = "updateMask"];</code>
   * @return A list containing the updateMask.
   */
  public com.google.protobuf.ProtocolStringList
      getUpdateMaskList() {
    return updateMask_;
  }
  /**
   * <pre>
   * changed fields
   * </pre>
   *
   * <code>repeated string update_mask = 4 [json_name = "updateMask"];</code>
   * @return The count of updateMask.
   */
  public int getUpdateMaskCount() {
    return updateMask_.size();
  }
  /**
   * <pre>
   * changed fields
   * </pre>
   *
   * <code>repeated string update_mask = 4 [json_name = "updateMask"];</code>
   * @param index The index of the element to return.
   * @return The updateMask at the given index.
   */
  public java.lang.String getUpdateMask(int index) {
    return updateMask_.get(index);
  }
  /**
   * <pre>
   * changed fields
   * </pre>
   *
   * <code>repeated string update_mask = 4 [json_name = "updateMask"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the updateMask at the given index.
   */
  public com.google.protobuf.ByteString
      getUpdateMaskBytes(int index) {
    return updateMask_.getByteString(index);
  }

  public static final int DESTINATION_FIELD_NUMBER = 5;
  private stream.api.live.Destination destination_;
  /**
   * <pre>
   * the updated destination
   * </pre>
   *
   * <code>.live.v21.Destination destination = 5 [json_name = "destination"];</code>
   * @return Whether the destination field is set.
   */
  @java.lang.Override
  public boolean hasDestination() {
    return destination_ != null;
  }
  /**
   * <pre>
   * the updated destination
   * </pre>
   *
   * <code>.live.v21.Destination destination = 5 [json_name = "destination"];</code>
   * @return The destination.
   */
  @java.lang.Override
  public stream.api.live.Destination getDestination() {
    return destination_ == null ? stream.api.live.Destination.getDefaultInstance() : destination_;
  }
  /**
   * <pre>
   * the updated destination
   * </pre>
   *
   * <code>.live.v21.Destination destination = 5 [json_name = "destination"];</code>
   */
  @java.lang.Override
  public stream.api.live.DestinationOrBuilder getDestinationOrBuilder() {
    return getDestination();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(collectionId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, collectionId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(projectId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, projectId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(destinationId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, destinationId_);
    }
    for (int i = 0; i < updateMask_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, updateMask_.getRaw(i));
    }
    if (destination_ != null) {
      output.writeMessage(5, getDestination());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(collectionId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, collectionId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(projectId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, projectId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(destinationId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, destinationId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < updateMask_.size(); i++) {
        dataSize += computeStringSizeNoTag(updateMask_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getUpdateMaskList().size();
    }
    if (destination_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getDestination());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof stream.api.live.DestinationUpdateEvent)) {
      return super.equals(obj);
    }
    stream.api.live.DestinationUpdateEvent other = (stream.api.live.DestinationUpdateEvent) obj;

    if (!getCollectionId()
        .equals(other.getCollectionId())) return false;
    if (!getProjectId()
        .equals(other.getProjectId())) return false;
    if (!getDestinationId()
        .equals(other.getDestinationId())) return false;
    if (!getUpdateMaskList()
        .equals(other.getUpdateMaskList())) return false;
    if (hasDestination() != other.hasDestination()) return false;
    if (hasDestination()) {
      if (!getDestination()
          .equals(other.getDestination())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COLLECTION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCollectionId().hashCode();
    hash = (37 * hash) + PROJECT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getProjectId().hashCode();
    hash = (37 * hash) + DESTINATION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDestinationId().hashCode();
    if (getUpdateMaskCount() > 0) {
      hash = (37 * hash) + UPDATE_MASK_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateMaskList().hashCode();
    }
    if (hasDestination()) {
      hash = (37 * hash) + DESTINATION_FIELD_NUMBER;
      hash = (53 * hash) + getDestination().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static stream.api.live.DestinationUpdateEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stream.api.live.DestinationUpdateEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stream.api.live.DestinationUpdateEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stream.api.live.DestinationUpdateEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stream.api.live.DestinationUpdateEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stream.api.live.DestinationUpdateEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stream.api.live.DestinationUpdateEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static stream.api.live.DestinationUpdateEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static stream.api.live.DestinationUpdateEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static stream.api.live.DestinationUpdateEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static stream.api.live.DestinationUpdateEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static stream.api.live.DestinationUpdateEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(stream.api.live.DestinationUpdateEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * a destination was updated
   * </pre>
   *
   * Protobuf type {@code live.v21.DestinationUpdateEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:live.v21.DestinationUpdateEvent)
      stream.api.live.DestinationUpdateEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return stream.api.live.Api.internal_static_live_v21_DestinationUpdateEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return stream.api.live.Api.internal_static_live_v21_DestinationUpdateEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              stream.api.live.DestinationUpdateEvent.class, stream.api.live.DestinationUpdateEvent.Builder.class);
    }

    // Construct using stream.api.live.DestinationUpdateEvent.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      collectionId_ = "";

      projectId_ = "";

      destinationId_ = "";

      updateMask_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (destinationBuilder_ == null) {
        destination_ = null;
      } else {
        destination_ = null;
        destinationBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return stream.api.live.Api.internal_static_live_v21_DestinationUpdateEvent_descriptor;
    }

    @java.lang.Override
    public stream.api.live.DestinationUpdateEvent getDefaultInstanceForType() {
      return stream.api.live.DestinationUpdateEvent.getDefaultInstance();
    }

    @java.lang.Override
    public stream.api.live.DestinationUpdateEvent build() {
      stream.api.live.DestinationUpdateEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public stream.api.live.DestinationUpdateEvent buildPartial() {
      stream.api.live.DestinationUpdateEvent result = new stream.api.live.DestinationUpdateEvent(this);
      int from_bitField0_ = bitField0_;
      result.collectionId_ = collectionId_;
      result.projectId_ = projectId_;
      result.destinationId_ = destinationId_;
      if (((bitField0_ & 0x00000001) != 0)) {
        updateMask_ = updateMask_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.updateMask_ = updateMask_;
      if (destinationBuilder_ == null) {
        result.destination_ = destination_;
      } else {
        result.destination_ = destinationBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof stream.api.live.DestinationUpdateEvent) {
        return mergeFrom((stream.api.live.DestinationUpdateEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(stream.api.live.DestinationUpdateEvent other) {
      if (other == stream.api.live.DestinationUpdateEvent.getDefaultInstance()) return this;
      if (!other.getCollectionId().isEmpty()) {
        collectionId_ = other.collectionId_;
        onChanged();
      }
      if (!other.getProjectId().isEmpty()) {
        projectId_ = other.projectId_;
        onChanged();
      }
      if (!other.getDestinationId().isEmpty()) {
        destinationId_ = other.destinationId_;
        onChanged();
      }
      if (!other.updateMask_.isEmpty()) {
        if (updateMask_.isEmpty()) {
          updateMask_ = other.updateMask_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureUpdateMaskIsMutable();
          updateMask_.addAll(other.updateMask_);
        }
        onChanged();
      }
      if (other.hasDestination()) {
        mergeDestination(other.getDestination());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      stream.api.live.DestinationUpdateEvent parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (stream.api.live.DestinationUpdateEvent) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object collectionId_ = "";
    /**
     * <pre>
     * collection which owns the project which owns the destination
     * </pre>
     *
     * <code>string collection_id = 1 [json_name = "collectionId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The collectionId.
     */
    public java.lang.String getCollectionId() {
      java.lang.Object ref = collectionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        collectionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * collection which owns the project which owns the destination
     * </pre>
     *
     * <code>string collection_id = 1 [json_name = "collectionId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The bytes for collectionId.
     */
    public com.google.protobuf.ByteString
        getCollectionIdBytes() {
      java.lang.Object ref = collectionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        collectionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * collection which owns the project which owns the destination
     * </pre>
     *
     * <code>string collection_id = 1 [json_name = "collectionId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The collectionId to set.
     * @return This builder for chaining.
     */
    public Builder setCollectionId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      collectionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * collection which owns the project which owns the destination
     * </pre>
     *
     * <code>string collection_id = 1 [json_name = "collectionId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearCollectionId() {
      
      collectionId_ = getDefaultInstance().getCollectionId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * collection which owns the project which owns the destination
     * </pre>
     *
     * <code>string collection_id = 1 [json_name = "collectionId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The bytes for collectionId to set.
     * @return This builder for chaining.
     */
    public Builder setCollectionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      collectionId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object projectId_ = "";
    /**
     * <pre>
     * project which owns the destination
     * </pre>
     *
     * <code>string project_id = 2 [json_name = "projectId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The projectId.
     */
    public java.lang.String getProjectId() {
      java.lang.Object ref = projectId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        projectId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * project which owns the destination
     * </pre>
     *
     * <code>string project_id = 2 [json_name = "projectId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The bytes for projectId.
     */
    public com.google.protobuf.ByteString
        getProjectIdBytes() {
      java.lang.Object ref = projectId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        projectId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * project which owns the destination
     * </pre>
     *
     * <code>string project_id = 2 [json_name = "projectId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The projectId to set.
     * @return This builder for chaining.
     */
    public Builder setProjectId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      projectId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * project which owns the destination
     * </pre>
     *
     * <code>string project_id = 2 [json_name = "projectId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearProjectId() {
      
      projectId_ = getDefaultInstance().getProjectId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * project which owns the destination
     * </pre>
     *
     * <code>string project_id = 2 [json_name = "projectId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The bytes for projectId to set.
     * @return This builder for chaining.
     */
    public Builder setProjectIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      projectId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object destinationId_ = "";
    /**
     * <pre>
     * destination id
     * </pre>
     *
     * <code>string destination_id = 3 [json_name = "destinationId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The destinationId.
     */
    public java.lang.String getDestinationId() {
      java.lang.Object ref = destinationId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destinationId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * destination id
     * </pre>
     *
     * <code>string destination_id = 3 [json_name = "destinationId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The bytes for destinationId.
     */
    public com.google.protobuf.ByteString
        getDestinationIdBytes() {
      java.lang.Object ref = destinationId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destinationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * destination id
     * </pre>
     *
     * <code>string destination_id = 3 [json_name = "destinationId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The destinationId to set.
     * @return This builder for chaining.
     */
    public Builder setDestinationId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      destinationId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * destination id
     * </pre>
     *
     * <code>string destination_id = 3 [json_name = "destinationId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearDestinationId() {
      
      destinationId_ = getDefaultInstance().getDestinationId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * destination id
     * </pre>
     *
     * <code>string destination_id = 3 [json_name = "destinationId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The bytes for destinationId to set.
     * @return This builder for chaining.
     */
    public Builder setDestinationIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      destinationId_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList updateMask_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureUpdateMaskIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        updateMask_ = new com.google.protobuf.LazyStringArrayList(updateMask_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * changed fields
     * </pre>
     *
     * <code>repeated string update_mask = 4 [json_name = "updateMask"];</code>
     * @return A list containing the updateMask.
     */
    public com.google.protobuf.ProtocolStringList
        getUpdateMaskList() {
      return updateMask_.getUnmodifiableView();
    }
    /**
     * <pre>
     * changed fields
     * </pre>
     *
     * <code>repeated string update_mask = 4 [json_name = "updateMask"];</code>
     * @return The count of updateMask.
     */
    public int getUpdateMaskCount() {
      return updateMask_.size();
    }
    /**
     * <pre>
     * changed fields
     * </pre>
     *
     * <code>repeated string update_mask = 4 [json_name = "updateMask"];</code>
     * @param index The index of the element to return.
     * @return The updateMask at the given index.
     */
    public java.lang.String getUpdateMask(int index) {
      return updateMask_.get(index);
    }
    /**
     * <pre>
     * changed fields
     * </pre>
     *
     * <code>repeated string update_mask = 4 [json_name = "updateMask"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the updateMask at the given index.
     */
    public com.google.protobuf.ByteString
        getUpdateMaskBytes(int index) {
      return updateMask_.getByteString(index);
    }
    /**
     * <pre>
     * changed fields
     * </pre>
     *
     * <code>repeated string update_mask = 4 [json_name = "updateMask"];</code>
     * @param index The index to set the value at.
     * @param value The updateMask to set.
     * @return This builder for chaining.
     */
    public Builder setUpdateMask(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureUpdateMaskIsMutable();
      updateMask_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * changed fields
     * </pre>
     *
     * <code>repeated string update_mask = 4 [json_name = "updateMask"];</code>
     * @param value The updateMask to add.
     * @return This builder for chaining.
     */
    public Builder addUpdateMask(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureUpdateMaskIsMutable();
      updateMask_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * changed fields
     * </pre>
     *
     * <code>repeated string update_mask = 4 [json_name = "updateMask"];</code>
     * @param values The updateMask to add.
     * @return This builder for chaining.
     */
    public Builder addAllUpdateMask(
        java.lang.Iterable<java.lang.String> values) {
      ensureUpdateMaskIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, updateMask_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * changed fields
     * </pre>
     *
     * <code>repeated string update_mask = 4 [json_name = "updateMask"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdateMask() {
      updateMask_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * changed fields
     * </pre>
     *
     * <code>repeated string update_mask = 4 [json_name = "updateMask"];</code>
     * @param value The bytes of the updateMask to add.
     * @return This builder for chaining.
     */
    public Builder addUpdateMaskBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureUpdateMaskIsMutable();
      updateMask_.add(value);
      onChanged();
      return this;
    }

    private stream.api.live.Destination destination_;
    private com.google.protobuf.SingleFieldBuilderV3<
        stream.api.live.Destination, stream.api.live.Destination.Builder, stream.api.live.DestinationOrBuilder> destinationBuilder_;
    /**
     * <pre>
     * the updated destination
     * </pre>
     *
     * <code>.live.v21.Destination destination = 5 [json_name = "destination"];</code>
     * @return Whether the destination field is set.
     */
    public boolean hasDestination() {
      return destinationBuilder_ != null || destination_ != null;
    }
    /**
     * <pre>
     * the updated destination
     * </pre>
     *
     * <code>.live.v21.Destination destination = 5 [json_name = "destination"];</code>
     * @return The destination.
     */
    public stream.api.live.Destination getDestination() {
      if (destinationBuilder_ == null) {
        return destination_ == null ? stream.api.live.Destination.getDefaultInstance() : destination_;
      } else {
        return destinationBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * the updated destination
     * </pre>
     *
     * <code>.live.v21.Destination destination = 5 [json_name = "destination"];</code>
     */
    public Builder setDestination(stream.api.live.Destination value) {
      if (destinationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        destination_ = value;
        onChanged();
      } else {
        destinationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * the updated destination
     * </pre>
     *
     * <code>.live.v21.Destination destination = 5 [json_name = "destination"];</code>
     */
    public Builder setDestination(
        stream.api.live.Destination.Builder builderForValue) {
      if (destinationBuilder_ == null) {
        destination_ = builderForValue.build();
        onChanged();
      } else {
        destinationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * the updated destination
     * </pre>
     *
     * <code>.live.v21.Destination destination = 5 [json_name = "destination"];</code>
     */
    public Builder mergeDestination(stream.api.live.Destination value) {
      if (destinationBuilder_ == null) {
        if (destination_ != null) {
          destination_ =
            stream.api.live.Destination.newBuilder(destination_).mergeFrom(value).buildPartial();
        } else {
          destination_ = value;
        }
        onChanged();
      } else {
        destinationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * the updated destination
     * </pre>
     *
     * <code>.live.v21.Destination destination = 5 [json_name = "destination"];</code>
     */
    public Builder clearDestination() {
      if (destinationBuilder_ == null) {
        destination_ = null;
        onChanged();
      } else {
        destination_ = null;
        destinationBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * the updated destination
     * </pre>
     *
     * <code>.live.v21.Destination destination = 5 [json_name = "destination"];</code>
     */
    public stream.api.live.Destination.Builder getDestinationBuilder() {
      
      onChanged();
      return getDestinationFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * the updated destination
     * </pre>
     *
     * <code>.live.v21.Destination destination = 5 [json_name = "destination"];</code>
     */
    public stream.api.live.DestinationOrBuilder getDestinationOrBuilder() {
      if (destinationBuilder_ != null) {
        return destinationBuilder_.getMessageOrBuilder();
      } else {
        return destination_ == null ?
            stream.api.live.Destination.getDefaultInstance() : destination_;
      }
    }
    /**
     * <pre>
     * the updated destination
     * </pre>
     *
     * <code>.live.v21.Destination destination = 5 [json_name = "destination"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        stream.api.live.Destination, stream.api.live.Destination.Builder, stream.api.live.DestinationOrBuilder> 
        getDestinationFieldBuilder() {
      if (destinationBuilder_ == null) {
        destinationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            stream.api.live.Destination, stream.api.live.Destination.Builder, stream.api.live.DestinationOrBuilder>(
                getDestination(),
                getParentForChildren(),
                isClean());
        destination_ = null;
      }
      return destinationBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:live.v21.DestinationUpdateEvent)
  }

  // @@protoc_insertion_point(class_scope:live.v21.DestinationUpdateEvent)
  private static final stream.api.live.DestinationUpdateEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new stream.api.live.DestinationUpdateEvent();
  }

  public static stream.api.live.DestinationUpdateEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DestinationUpdateEvent>
      PARSER = new com.google.protobuf.AbstractParser<DestinationUpdateEvent>() {
    @java.lang.Override
    public DestinationUpdateEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DestinationUpdateEvent(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DestinationUpdateEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DestinationUpdateEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public stream.api.live.DestinationUpdateEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

