/* ---------------------------------------------------------------------------------------------
 * Copyright (c) Infiniscene, Inc. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 * -------------------------------------------------------------------------------------------- */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: live/v21/api.proto

package stream.api.live;

/**
 * <pre>
 * the parameters of the encoding
 * </pre>
 *
 * Protobuf type {@code live.v21.Encoding}
 */
public final class Encoding extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:live.v21.Encoding)
    EncodingOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Encoding.newBuilder() to construct.
  private Encoding(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Encoding() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Encoding();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Encoding(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            stream.api.live.VideoEncoding.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) != 0)) {
              subBuilder = video_.toBuilder();
            }
            video_ = input.readMessage(stream.api.live.VideoEncoding.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(video_);
              video_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 18: {
            stream.api.live.AudioEncoding.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) != 0)) {
              subBuilder = audio_.toBuilder();
            }
            audio_ = input.readMessage(stream.api.live.AudioEncoding.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(audio_);
              audio_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return stream.api.live.Api.internal_static_live_v21_Encoding_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return stream.api.live.Api.internal_static_live_v21_Encoding_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            stream.api.live.Encoding.class, stream.api.live.Encoding.Builder.class);
  }

  private int bitField0_;
  public static final int VIDEO_FIELD_NUMBER = 1;
  private stream.api.live.VideoEncoding video_;
  /**
   * <pre>
   * the video parameters of the encoding
   * </pre>
   *
   * <code>optional .live.v21.VideoEncoding video = 1 [json_name = "video", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the video field is set.
   */
  @java.lang.Override
  public boolean hasVideo() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * the video parameters of the encoding
   * </pre>
   *
   * <code>optional .live.v21.VideoEncoding video = 1 [json_name = "video", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The video.
   */
  @java.lang.Override
  public stream.api.live.VideoEncoding getVideo() {
    return video_ == null ? stream.api.live.VideoEncoding.getDefaultInstance() : video_;
  }
  /**
   * <pre>
   * the video parameters of the encoding
   * </pre>
   *
   * <code>optional .live.v21.VideoEncoding video = 1 [json_name = "video", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   */
  @java.lang.Override
  public stream.api.live.VideoEncodingOrBuilder getVideoOrBuilder() {
    return video_ == null ? stream.api.live.VideoEncoding.getDefaultInstance() : video_;
  }

  public static final int AUDIO_FIELD_NUMBER = 2;
  private stream.api.live.AudioEncoding audio_;
  /**
   * <pre>
   * the audio parameters of the encoding
   * </pre>
   *
   * <code>optional .live.v21.AudioEncoding audio = 2 [json_name = "audio", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the audio field is set.
   */
  @java.lang.Override
  public boolean hasAudio() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * the audio parameters of the encoding
   * </pre>
   *
   * <code>optional .live.v21.AudioEncoding audio = 2 [json_name = "audio", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The audio.
   */
  @java.lang.Override
  public stream.api.live.AudioEncoding getAudio() {
    return audio_ == null ? stream.api.live.AudioEncoding.getDefaultInstance() : audio_;
  }
  /**
   * <pre>
   * the audio parameters of the encoding
   * </pre>
   *
   * <code>optional .live.v21.AudioEncoding audio = 2 [json_name = "audio", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   */
  @java.lang.Override
  public stream.api.live.AudioEncodingOrBuilder getAudioOrBuilder() {
    return audio_ == null ? stream.api.live.AudioEncoding.getDefaultInstance() : audio_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getVideo());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getAudio());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getVideo());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getAudio());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof stream.api.live.Encoding)) {
      return super.equals(obj);
    }
    stream.api.live.Encoding other = (stream.api.live.Encoding) obj;

    if (hasVideo() != other.hasVideo()) return false;
    if (hasVideo()) {
      if (!getVideo()
          .equals(other.getVideo())) return false;
    }
    if (hasAudio() != other.hasAudio()) return false;
    if (hasAudio()) {
      if (!getAudio()
          .equals(other.getAudio())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasVideo()) {
      hash = (37 * hash) + VIDEO_FIELD_NUMBER;
      hash = (53 * hash) + getVideo().hashCode();
    }
    if (hasAudio()) {
      hash = (37 * hash) + AUDIO_FIELD_NUMBER;
      hash = (53 * hash) + getAudio().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static stream.api.live.Encoding parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stream.api.live.Encoding parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stream.api.live.Encoding parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stream.api.live.Encoding parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stream.api.live.Encoding parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stream.api.live.Encoding parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stream.api.live.Encoding parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static stream.api.live.Encoding parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static stream.api.live.Encoding parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static stream.api.live.Encoding parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static stream.api.live.Encoding parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static stream.api.live.Encoding parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(stream.api.live.Encoding prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * the parameters of the encoding
   * </pre>
   *
   * Protobuf type {@code live.v21.Encoding}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:live.v21.Encoding)
      stream.api.live.EncodingOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return stream.api.live.Api.internal_static_live_v21_Encoding_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return stream.api.live.Api.internal_static_live_v21_Encoding_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              stream.api.live.Encoding.class, stream.api.live.Encoding.Builder.class);
    }

    // Construct using stream.api.live.Encoding.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getVideoFieldBuilder();
        getAudioFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (videoBuilder_ == null) {
        video_ = null;
      } else {
        videoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (audioBuilder_ == null) {
        audio_ = null;
      } else {
        audioBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return stream.api.live.Api.internal_static_live_v21_Encoding_descriptor;
    }

    @java.lang.Override
    public stream.api.live.Encoding getDefaultInstanceForType() {
      return stream.api.live.Encoding.getDefaultInstance();
    }

    @java.lang.Override
    public stream.api.live.Encoding build() {
      stream.api.live.Encoding result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public stream.api.live.Encoding buildPartial() {
      stream.api.live.Encoding result = new stream.api.live.Encoding(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        if (videoBuilder_ == null) {
          result.video_ = video_;
        } else {
          result.video_ = videoBuilder_.build();
        }
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        if (audioBuilder_ == null) {
          result.audio_ = audio_;
        } else {
          result.audio_ = audioBuilder_.build();
        }
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof stream.api.live.Encoding) {
        return mergeFrom((stream.api.live.Encoding)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(stream.api.live.Encoding other) {
      if (other == stream.api.live.Encoding.getDefaultInstance()) return this;
      if (other.hasVideo()) {
        mergeVideo(other.getVideo());
      }
      if (other.hasAudio()) {
        mergeAudio(other.getAudio());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      stream.api.live.Encoding parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (stream.api.live.Encoding) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private stream.api.live.VideoEncoding video_;
    private com.google.protobuf.SingleFieldBuilderV3<
        stream.api.live.VideoEncoding, stream.api.live.VideoEncoding.Builder, stream.api.live.VideoEncodingOrBuilder> videoBuilder_;
    /**
     * <pre>
     * the video parameters of the encoding
     * </pre>
     *
     * <code>optional .live.v21.VideoEncoding video = 1 [json_name = "video", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return Whether the video field is set.
     */
    public boolean hasVideo() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * the video parameters of the encoding
     * </pre>
     *
     * <code>optional .live.v21.VideoEncoding video = 1 [json_name = "video", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The video.
     */
    public stream.api.live.VideoEncoding getVideo() {
      if (videoBuilder_ == null) {
        return video_ == null ? stream.api.live.VideoEncoding.getDefaultInstance() : video_;
      } else {
        return videoBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * the video parameters of the encoding
     * </pre>
     *
     * <code>optional .live.v21.VideoEncoding video = 1 [json_name = "video", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder setVideo(stream.api.live.VideoEncoding value) {
      if (videoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        video_ = value;
        onChanged();
      } else {
        videoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * the video parameters of the encoding
     * </pre>
     *
     * <code>optional .live.v21.VideoEncoding video = 1 [json_name = "video", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder setVideo(
        stream.api.live.VideoEncoding.Builder builderForValue) {
      if (videoBuilder_ == null) {
        video_ = builderForValue.build();
        onChanged();
      } else {
        videoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * the video parameters of the encoding
     * </pre>
     *
     * <code>optional .live.v21.VideoEncoding video = 1 [json_name = "video", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder mergeVideo(stream.api.live.VideoEncoding value) {
      if (videoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
            video_ != null &&
            video_ != stream.api.live.VideoEncoding.getDefaultInstance()) {
          video_ =
            stream.api.live.VideoEncoding.newBuilder(video_).mergeFrom(value).buildPartial();
        } else {
          video_ = value;
        }
        onChanged();
      } else {
        videoBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * the video parameters of the encoding
     * </pre>
     *
     * <code>optional .live.v21.VideoEncoding video = 1 [json_name = "video", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder clearVideo() {
      if (videoBuilder_ == null) {
        video_ = null;
        onChanged();
      } else {
        videoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <pre>
     * the video parameters of the encoding
     * </pre>
     *
     * <code>optional .live.v21.VideoEncoding video = 1 [json_name = "video", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public stream.api.live.VideoEncoding.Builder getVideoBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getVideoFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * the video parameters of the encoding
     * </pre>
     *
     * <code>optional .live.v21.VideoEncoding video = 1 [json_name = "video", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public stream.api.live.VideoEncodingOrBuilder getVideoOrBuilder() {
      if (videoBuilder_ != null) {
        return videoBuilder_.getMessageOrBuilder();
      } else {
        return video_ == null ?
            stream.api.live.VideoEncoding.getDefaultInstance() : video_;
      }
    }
    /**
     * <pre>
     * the video parameters of the encoding
     * </pre>
     *
     * <code>optional .live.v21.VideoEncoding video = 1 [json_name = "video", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        stream.api.live.VideoEncoding, stream.api.live.VideoEncoding.Builder, stream.api.live.VideoEncodingOrBuilder> 
        getVideoFieldBuilder() {
      if (videoBuilder_ == null) {
        videoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            stream.api.live.VideoEncoding, stream.api.live.VideoEncoding.Builder, stream.api.live.VideoEncodingOrBuilder>(
                getVideo(),
                getParentForChildren(),
                isClean());
        video_ = null;
      }
      return videoBuilder_;
    }

    private stream.api.live.AudioEncoding audio_;
    private com.google.protobuf.SingleFieldBuilderV3<
        stream.api.live.AudioEncoding, stream.api.live.AudioEncoding.Builder, stream.api.live.AudioEncodingOrBuilder> audioBuilder_;
    /**
     * <pre>
     * the audio parameters of the encoding
     * </pre>
     *
     * <code>optional .live.v21.AudioEncoding audio = 2 [json_name = "audio", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return Whether the audio field is set.
     */
    public boolean hasAudio() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * the audio parameters of the encoding
     * </pre>
     *
     * <code>optional .live.v21.AudioEncoding audio = 2 [json_name = "audio", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The audio.
     */
    public stream.api.live.AudioEncoding getAudio() {
      if (audioBuilder_ == null) {
        return audio_ == null ? stream.api.live.AudioEncoding.getDefaultInstance() : audio_;
      } else {
        return audioBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * the audio parameters of the encoding
     * </pre>
     *
     * <code>optional .live.v21.AudioEncoding audio = 2 [json_name = "audio", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder setAudio(stream.api.live.AudioEncoding value) {
      if (audioBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        audio_ = value;
        onChanged();
      } else {
        audioBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <pre>
     * the audio parameters of the encoding
     * </pre>
     *
     * <code>optional .live.v21.AudioEncoding audio = 2 [json_name = "audio", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder setAudio(
        stream.api.live.AudioEncoding.Builder builderForValue) {
      if (audioBuilder_ == null) {
        audio_ = builderForValue.build();
        onChanged();
      } else {
        audioBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <pre>
     * the audio parameters of the encoding
     * </pre>
     *
     * <code>optional .live.v21.AudioEncoding audio = 2 [json_name = "audio", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder mergeAudio(stream.api.live.AudioEncoding value) {
      if (audioBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
            audio_ != null &&
            audio_ != stream.api.live.AudioEncoding.getDefaultInstance()) {
          audio_ =
            stream.api.live.AudioEncoding.newBuilder(audio_).mergeFrom(value).buildPartial();
        } else {
          audio_ = value;
        }
        onChanged();
      } else {
        audioBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <pre>
     * the audio parameters of the encoding
     * </pre>
     *
     * <code>optional .live.v21.AudioEncoding audio = 2 [json_name = "audio", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder clearAudio() {
      if (audioBuilder_ == null) {
        audio_ = null;
        onChanged();
      } else {
        audioBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <pre>
     * the audio parameters of the encoding
     * </pre>
     *
     * <code>optional .live.v21.AudioEncoding audio = 2 [json_name = "audio", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public stream.api.live.AudioEncoding.Builder getAudioBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getAudioFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * the audio parameters of the encoding
     * </pre>
     *
     * <code>optional .live.v21.AudioEncoding audio = 2 [json_name = "audio", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public stream.api.live.AudioEncodingOrBuilder getAudioOrBuilder() {
      if (audioBuilder_ != null) {
        return audioBuilder_.getMessageOrBuilder();
      } else {
        return audio_ == null ?
            stream.api.live.AudioEncoding.getDefaultInstance() : audio_;
      }
    }
    /**
     * <pre>
     * the audio parameters of the encoding
     * </pre>
     *
     * <code>optional .live.v21.AudioEncoding audio = 2 [json_name = "audio", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        stream.api.live.AudioEncoding, stream.api.live.AudioEncoding.Builder, stream.api.live.AudioEncodingOrBuilder> 
        getAudioFieldBuilder() {
      if (audioBuilder_ == null) {
        audioBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            stream.api.live.AudioEncoding, stream.api.live.AudioEncoding.Builder, stream.api.live.AudioEncodingOrBuilder>(
                getAudio(),
                getParentForChildren(),
                isClean());
        audio_ = null;
      }
      return audioBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:live.v21.Encoding)
  }

  // @@protoc_insertion_point(class_scope:live.v21.Encoding)
  private static final stream.api.live.Encoding DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new stream.api.live.Encoding();
  }

  public static stream.api.live.Encoding getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Encoding>
      PARSER = new com.google.protobuf.AbstractParser<Encoding>() {
    @java.lang.Override
    public Encoding parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Encoding(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Encoding> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Encoding> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public stream.api.live.Encoding getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

