/* ---------------------------------------------------------------------------------------------
 * Copyright (c) Infiniscene, Inc. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 * -------------------------------------------------------------------------------------------- */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: live/v21/api.proto

package stream.api.live;

public interface GuestAccessTokenDirectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:live.v21.GuestAccessTokenDirect)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * display name of the guest (used to generate webrtc particpant name)
   * </pre>
   *
   * <code>string display_name = 1 [json_name = "displayName", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The displayName.
   */
  java.lang.String getDisplayName();
  /**
   * <pre>
   * display name of the guest (used to generate webrtc particpant name)
   * </pre>
   *
   * <code>string display_name = 1 [json_name = "displayName", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for displayName.
   */
  com.google.protobuf.ByteString
      getDisplayNameBytes();

  /**
   * <pre>
   * service-specific user id (used for record auditing purposes)
   * </pre>
   *
   * <code>optional string service_user_id = 2 [json_name = "serviceUserId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the serviceUserId field is set.
   */
  boolean hasServiceUserId();
  /**
   * <pre>
   * service-specific user id (used for record auditing purposes)
   * </pre>
   *
   * <code>optional string service_user_id = 2 [json_name = "serviceUserId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The serviceUserId.
   */
  java.lang.String getServiceUserId();
  /**
   * <pre>
   * service-specific user id (used for record auditing purposes)
   * </pre>
   *
   * <code>optional string service_user_id = 2 [json_name = "serviceUserId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for serviceUserId.
   */
  com.google.protobuf.ByteString
      getServiceUserIdBytes();
}
