/* ---------------------------------------------------------------------------------------------
 * Copyright (c) Infiniscene, Inc. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 * -------------------------------------------------------------------------------------------- */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: live/v21/api.proto

package stream.api.live;

public interface ProjectBroadcastStateEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:live.v21.ProjectBroadcastStateEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * collection which owns the project
   * </pre>
   *
   * <code>string collection_id = 1 [json_name = "collectionId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The collectionId.
   */
  java.lang.String getCollectionId();
  /**
   * <pre>
   * collection which owns the project
   * </pre>
   *
   * <code>string collection_id = 1 [json_name = "collectionId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for collectionId.
   */
  com.google.protobuf.ByteString
      getCollectionIdBytes();

  /**
   * <pre>
   * project id
   * </pre>
   *
   * <code>string project_id = 2 [json_name = "projectId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The projectId.
   */
  java.lang.String getProjectId();
  /**
   * <pre>
   * project id
   * </pre>
   *
   * <code>string project_id = 2 [json_name = "projectId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for projectId.
   */
  com.google.protobuf.ByteString
      getProjectIdBytes();

  /**
   * <pre>
   * the id of the broadcast
   * </pre>
   *
   * <code>string broadcast_id = 3 [json_name = "broadcastId"];</code>
   * @return The broadcastId.
   */
  java.lang.String getBroadcastId();
  /**
   * <pre>
   * the id of the broadcast
   * </pre>
   *
   * <code>string broadcast_id = 3 [json_name = "broadcastId"];</code>
   * @return The bytes for broadcastId.
   */
  com.google.protobuf.ByteString
      getBroadcastIdBytes();

  /**
   * <code>.live.v21.ProjectBroadcastPhase phase = 4 [json_name = "phase"];</code>
   * @return Whether the phase field is set.
   */
  boolean hasPhase();
  /**
   * <code>.live.v21.ProjectBroadcastPhase phase = 4 [json_name = "phase"];</code>
   * @return The enum numeric value on the wire for phase.
   */
  int getPhaseValue();
  /**
   * <code>.live.v21.ProjectBroadcastPhase phase = 4 [json_name = "phase"];</code>
   * @return The phase.
   */
  stream.api.live.ProjectBroadcastPhase getPhase();

  /**
   * <code>.live.v21.ProjectBroadcastError error = 5 [json_name = "error"];</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.live.v21.ProjectBroadcastError error = 5 [json_name = "error"];</code>
   * @return The enum numeric value on the wire for error.
   */
  int getErrorValue();
  /**
   * <code>.live.v21.ProjectBroadcastError error = 5 [json_name = "error"];</code>
   * @return The error.
   */
  stream.api.live.ProjectBroadcastError getError();

  public stream.api.live.ProjectBroadcastStateEvent.TypeCase getTypeCase();
}
