/* ---------------------------------------------------------------------------------------------
 * Copyright (c) Infiniscene, Inc. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 * -------------------------------------------------------------------------------------------- */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: live/v21/api.proto

package stream.api.live;

public interface ProjectBroadcastStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:live.v21.ProjectBroadcastStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * collection which owns the project which owns the broadcast
   * </pre>
   *
   * <code>string collection_id = 1 [json_name = "collectionId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The collectionId.
   */
  java.lang.String getCollectionId();
  /**
   * <pre>
   * collection which owns the project which owns the broadcast
   * </pre>
   *
   * <code>string collection_id = 1 [json_name = "collectionId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for collectionId.
   */
  com.google.protobuf.ByteString
      getCollectionIdBytes();

  /**
   * <pre>
   * project which owns the broadcast
   * </pre>
   *
   * <code>string project_id = 2 [json_name = "projectId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The projectId.
   */
  java.lang.String getProjectId();
  /**
   * <pre>
   * project which owns the broadcast
   * </pre>
   *
   * <code>string project_id = 2 [json_name = "projectId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for projectId.
   */
  com.google.protobuf.ByteString
      getProjectIdBytes();

  /**
   * <code>optional string broadcast_id = 3 [json_name = "broadcastId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the broadcastId field is set.
   */
  boolean hasBroadcastId();
  /**
   * <code>optional string broadcast_id = 3 [json_name = "broadcastId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The broadcastId.
   */
  java.lang.String getBroadcastId();
  /**
   * <code>optional string broadcast_id = 3 [json_name = "broadcastId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for broadcastId.
   */
  com.google.protobuf.ByteString
      getBroadcastIdBytes();

  /**
   * <pre>
   * broadcast duration (ms)
   * </pre>
   *
   * <code>optional uint32 duration = 4 [json_name = "duration", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the duration field is set.
   */
  boolean hasDuration();
  /**
   * <pre>
   * broadcast duration (ms)
   * </pre>
   *
   * <code>optional uint32 duration = 4 [json_name = "duration", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The duration.
   */
  int getDuration();

  /**
   * <pre>
   * broadcast start timestamp (ISO8601 UTC)
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp start = 5 [json_name = "start", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the start field is set.
   */
  boolean hasStart();
  /**
   * <pre>
   * broadcast start timestamp (ISO8601 UTC)
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp start = 5 [json_name = "start", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The start.
   */
  com.google.protobuf.Timestamp getStart();
  /**
   * <pre>
   * broadcast start timestamp (ISO8601 UTC)
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp start = 5 [json_name = "start", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   */
  com.google.protobuf.TimestampOrBuilder getStartOrBuilder();

  /**
   * <pre>
   * broadcast stop timestamp (ISO8601 UTC)
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp stop = 6 [json_name = "stop", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the stop field is set.
   */
  boolean hasStop();
  /**
   * <pre>
   * broadcast stop timestamp (ISO8601 UTC)
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp stop = 6 [json_name = "stop", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The stop.
   */
  com.google.protobuf.Timestamp getStop();
  /**
   * <pre>
   * broadcast stop timestamp (ISO8601 UTC)
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp stop = 6 [json_name = "stop", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   */
  com.google.protobuf.TimestampOrBuilder getStopOrBuilder();

  /**
   * <pre>
   * broadcast phase
   * </pre>
   *
   * <code>.live.v21.ProjectBroadcastPhase phase = 7 [json_name = "phase", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The enum numeric value on the wire for phase.
   */
  int getPhaseValue();
  /**
   * <pre>
   * broadcast phase
   * </pre>
   *
   * <code>.live.v21.ProjectBroadcastPhase phase = 7 [json_name = "phase", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The phase.
   */
  stream.api.live.ProjectBroadcastPhase getPhase();

  /**
   * <pre>
   * region broadcast is located
   * </pre>
   *
   * <code>optional .live.v21.Region region = 8 [json_name = "region", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the region field is set.
   */
  boolean hasRegion();
  /**
   * <pre>
   * region broadcast is located
   * </pre>
   *
   * <code>optional .live.v21.Region region = 8 [json_name = "region", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The enum numeric value on the wire for region.
   */
  int getRegionValue();
  /**
   * <pre>
   * region broadcast is located
   * </pre>
   *
   * <code>optional .live.v21.Region region = 8 [json_name = "region", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The region.
   */
  stream.api.live.Region getRegion();

  /**
   * <pre>
   * datacenter broadcast is located
   * </pre>
   *
   * <code>optional string datacenter = 9 [json_name = "datacenter", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the datacenter field is set.
   */
  boolean hasDatacenter();
  /**
   * <pre>
   * datacenter broadcast is located
   * </pre>
   *
   * <code>optional string datacenter = 9 [json_name = "datacenter", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The datacenter.
   */
  java.lang.String getDatacenter();
  /**
   * <pre>
   * datacenter broadcast is located
   * </pre>
   *
   * <code>optional string datacenter = 9 [json_name = "datacenter", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for datacenter.
   */
  com.google.protobuf.ByteString
      getDatacenterBytes();
}
