/* ---------------------------------------------------------------------------------------------
 * Copyright (c) Infiniscene, Inc. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 * -------------------------------------------------------------------------------------------- */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: live/v21/api.proto

package stream.api.live;

/**
 * <pre>
 * boolean logic for trigger
 * </pre>
 *
 * Protobuf enum {@code live.v21.SourceTriggerAction}
 */
public enum SourceTriggerAction
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SOURCE_TRIGGER_ACTION_UNSPECIFIED = 0;</code>
   */
  SOURCE_TRIGGER_ACTION_UNSPECIFIED(0),
  /**
   * <code>SOURCE_TRIGGER_ACTION_IGNORE = 1;</code>
   */
  SOURCE_TRIGGER_ACTION_IGNORE(1),
  /**
   * <pre>
   * SOURCE_TRIGGER_ACTION_AND = 2;
   * </pre>
   *
   * <code>SOURCE_TRIGGER_ACTION_OR = 3;</code>
   */
  SOURCE_TRIGGER_ACTION_OR(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>SOURCE_TRIGGER_ACTION_UNSPECIFIED = 0;</code>
   */
  public static final int SOURCE_TRIGGER_ACTION_UNSPECIFIED_VALUE = 0;
  /**
   * <code>SOURCE_TRIGGER_ACTION_IGNORE = 1;</code>
   */
  public static final int SOURCE_TRIGGER_ACTION_IGNORE_VALUE = 1;
  /**
   * <pre>
   * SOURCE_TRIGGER_ACTION_AND = 2;
   * </pre>
   *
   * <code>SOURCE_TRIGGER_ACTION_OR = 3;</code>
   */
  public static final int SOURCE_TRIGGER_ACTION_OR_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static SourceTriggerAction valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static SourceTriggerAction forNumber(int value) {
    switch (value) {
      case 0: return SOURCE_TRIGGER_ACTION_UNSPECIFIED;
      case 1: return SOURCE_TRIGGER_ACTION_IGNORE;
      case 3: return SOURCE_TRIGGER_ACTION_OR;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SourceTriggerAction>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      SourceTriggerAction> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SourceTriggerAction>() {
          public SourceTriggerAction findValueByNumber(int number) {
            return SourceTriggerAction.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return stream.api.live.Api.getDescriptor().getEnumTypes().get(9);
  }

  private static final SourceTriggerAction[] VALUES = values();

  public static SourceTriggerAction valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private SourceTriggerAction(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:live.v21.SourceTriggerAction)
}

