/* ---------------------------------------------------------------------------------------------
 * Copyright (c) Infiniscene, Inc. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 * -------------------------------------------------------------------------------------------- */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: live/v21/api.proto

package stream.api.live;

public interface UpdateSourceInProjectResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:live.v21.UpdateSourceInProjectResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * updated project
   * </pre>
   *
   * <code>.live.v21.Project project = 1 [json_name = "project"];</code>
   * @return Whether the project field is set.
   */
  boolean hasProject();
  /**
   * <pre>
   * updated project
   * </pre>
   *
   * <code>.live.v21.Project project = 1 [json_name = "project"];</code>
   * @return The project.
   */
  stream.api.live.Project getProject();
  /**
   * <pre>
   * updated project
   * </pre>
   *
   * <code>.live.v21.Project project = 1 [json_name = "project"];</code>
   */
  stream.api.live.ProjectOrBuilder getProjectOrBuilder();
}
