/* ---------------------------------------------------------------------------------------------
 * Copyright (c) Infiniscene, Inc. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 * -------------------------------------------------------------------------------------------- */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: live/v21/api.proto

package stream.api.live;

/**
 * <pre>
 * video encoding rate control mode
 * </pre>
 *
 * Protobuf enum {@code live.v21.VideoCodecRateControlMode}
 */
public enum VideoCodecRateControlMode
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>VIDEO_CODEC_RATE_CONTROL_MODE_UNSPECIFIED = 0;</code>
   */
  VIDEO_CODEC_RATE_CONTROL_MODE_UNSPECIFIED(0),
  /**
   * <pre>
   * constant bit rate encoding
   * </pre>
   *
   * <code>VIDEO_CODEC_RATE_CONTROL_MODE_CBR = 1;</code>
   */
  VIDEO_CODEC_RATE_CONTROL_MODE_CBR(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>VIDEO_CODEC_RATE_CONTROL_MODE_UNSPECIFIED = 0;</code>
   */
  public static final int VIDEO_CODEC_RATE_CONTROL_MODE_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * constant bit rate encoding
   * </pre>
   *
   * <code>VIDEO_CODEC_RATE_CONTROL_MODE_CBR = 1;</code>
   */
  public static final int VIDEO_CODEC_RATE_CONTROL_MODE_CBR_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static VideoCodecRateControlMode valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static VideoCodecRateControlMode forNumber(int value) {
    switch (value) {
      case 0: return VIDEO_CODEC_RATE_CONTROL_MODE_UNSPECIFIED;
      case 1: return VIDEO_CODEC_RATE_CONTROL_MODE_CBR;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<VideoCodecRateControlMode>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      VideoCodecRateControlMode> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<VideoCodecRateControlMode>() {
          public VideoCodecRateControlMode findValueByNumber(int number) {
            return VideoCodecRateControlMode.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return stream.api.live.Api.getDescriptor().getEnumTypes().get(7);
  }

  private static final VideoCodecRateControlMode[] VALUES = values();

  public static VideoCodecRateControlMode valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private VideoCodecRateControlMode(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:live.v21.VideoCodecRateControlMode)
}

